## ドライブのマウント

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from google.colab import userdata
HF_TOKEN = userdata.get('HF_TOKEN2')

In [ ]:
!pip install -q huggingface_hub
from huggingface_hub import login
login(HF_TOKEN) # ここでトークンを入力してね（Write権限があるトークンが必要だよ）

# 環境設定
  - 標準コード1と同様、まずは環境設定を行います。

In [ ]:
# ============================================================
# 0) 依存関係の固定（Colabの“環境ブレ”対策）
# ============================================================
# Colab（無料版）は、ある日突然プリインストール版が変わり、
# それまで動いていた学習コードが壊れることが頻繁にあります。
# そのため、このセルでは「一度全部消す → 互換が確認できたバージョンを入れ直す」
# という“強制的な再現性確保”をしています。
#
# やりがちな事故：
# - 既に入っているパッケージと混ざって「importは通るが実行で落ちる」
# - transformers / trl / unsloth の相性不一致で、謎エラーや速度低下が起きる
#
# ※このセルは“おまじない”ではなく「再現性のための重要工程」です。

#!pip -q uninstall -y numpy pandas datasets trl transformers accelerate peft unsloth unsloth-zoo bitsandbytes xformers
!uv pip install "numpy==2.0.2" "pandas==2.2.2"

# unsloth-zoo が要求する範囲に合わせる
# ここでは Unsloth と相性の良い transformers / trl / accelerate / peft / bitsandbytes を固定します。
# 特に transformers は細かいバージョン差で挙動が変わりやすいので固定が重要です。
!uv pip install \
  "datasets==4.3.0" \
  "trl==0.24.0" \
  "transformers==4.56.2" \
  "accelerate==1.4.0" \
  "peft==0.13.2" \
  "bitsandbytes==0.45.0"

# unsloth / zoo を同系列で揃える（zoo側の要求に合わせる）
# Unsloth本体と unsloth-zoo は“セット運用”が基本です。片方だけ上げると壊れがちです。
!uv pip install "unsloth-zoo==2025.12.7" "unsloth==2025.12.7"

Using Python 3.12.12 environment at: /usr
Audited 2 packages in 464ms
Using Python 3.12.12 environment at: /usr
Resolved 68 packages in 490ms
Uninstalled 2 packages in 58ms
Installed 2 packages in 33ms
 - bitsandbytes==0.49.1
 + bitsandbytes==0.45.0
 - peft==0.18.1
 + peft==0.13.2
Using Python 3.12.12 environment at: /usr
Resolved 86 packages in 247ms
Uninstalled 3 packages in 25ms
Installed 3 packages in 24ms
 - bitsandbytes==0.45.0
 + bitsandbytes==0.49.1
 - unsloth==2026.1.4
 + unsloth==2025.12.7
 - unsloth-zoo==2026.1.4
 + unsloth-zoo==2025.12.7

In [ ]:
# huggingface_hubを最新にして整合性を合わせる
!pip install --upgrade huggingface_hub unsloth

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (0.36.2)
Collecting huggingface_hub
  Using cached huggingface_hub-1.4.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: unsloth in /usr/local/lib/python3.12/dist-packages (2025.12.7)
Collecting unsloth
  Using cached unsloth-2026.1.4-py3-none-any.whl.metadata (66 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.20.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.5.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.21.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Collecting unsloth_zoo>=2026.1.4 (from unsloth)
  Using cached unsloth_zoo-2026.1.4-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.46.3)
Requirement already satisfied: torch>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.9.0+cu126)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.24.0+cu126)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.9.5)
Requirement already satisfied: tyro in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.0.6)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.29.5)
Requirement already satisfied: xformers>=0.0.27.post2 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.0.33.post1)
Requirement already satisfied: bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.49.1)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (3.5.0)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.2.1)
Requirement already satisfied: datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.3.0)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.4.0)
Collecting peft!=0.11.0,>=0.18.0 (from unsloth)
  Using cached peft-0.18.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: hf_transfer in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.1.9)
Requirement already satisfied: diffusers in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.36.0)
Requirement already satisfied: transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,<=4.57.6,>=4.51.3 in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.56.2)
Requirement already satisfied: trl!=0.19.0,<=0.24.0,>=0.18.2 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.34.1->unsloth) (0.7.0)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (23.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.70.16)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.11.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,<=4.57.6,>=4.51.3->unsloth) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,<=4.57.6,>=4.51.3->unsloth) (0.22.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.5.0)
Requirement already satisfied: torchao>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (0.15.0)
Requirement already satisfied: cut_cross_entropy in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (25.1.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (11.3.0)
Requirement already satisfied: msgspec in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (0.20.0)
Requirement already satisfied: importlib_metadata in /usr/local/lib/python3.12/dist-packages (from diffusers->unsloth) (8.7.1)
Requirement already satisfied: docstring-parser>=0.15 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (0.17.0)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (4.4.4)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.13.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.4.0->unsloth) (1.3.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata->diffusers->unsloth) (3.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.4.0->unsloth) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.17.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface_hub) (8.3.1)
Using cached unsloth-2026.1.4-py3-none-any.whl (405 kB)
Using cached peft-0.18.1-py3-none-any.whl (556 kB)
Using cached unsloth_zoo-2026.1.4-py3-none-any.whl (310 kB)
Installing collected packages: peft, unsloth_zoo, unsloth
  Attempting uninstall: peft
    Found existing installation: peft 0.13.2
    Uninstalling peft-0.13.2:
      Successfully uninstalled peft-0.13.2
  Attempting uninstall: unsloth_zoo
    Found existing installation: unsloth_zoo 2025.12.7
    Uninstalling unsloth_zoo-2025.12.7:
      Successfully uninstalled unsloth_zoo-2025.12.7
  Attempting uninstall: unsloth
    Found existing installation: unsloth 2025.12.7
    Uninstalling unsloth-2025.12.7:
      Successfully uninstalled unsloth-2025.12.7
Successfully installed peft-0.18.1 unsloth-2026.1.4 unsloth_zoo-2026.1.4

## DPO１回目

### データセットのロード

In [ ]:
from datasets import load_dataset

# 1. 保存したjsonlファイルを読み込む
# 先ほどのスクリプトと同じディレクトリにあることを想定しているよ
data_files = {
    "train": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/dpo_train.jsonl",
    "eval": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/dpo_train.jsonl"
}

# json形式でロード
dataset = load_dataset("json", data_files=data_files)

# 2. train と eval に切り分け
train_dataset = dataset["train"]
eval_dataset = dataset["eval"]

# 3. 中身の確認（デバッグ用：最初の1件を表示）
print("--- Train Dataset Sample ---")
print(train_dataset[0])
print(f"\nTrain size: {len(train_dataset)}, Eval size: {len(eval_dataset)}")

Generating train split: 0 examples [00:00, ? examples/s]

Generating eval split: 0 examples [00:00, ? examples/s]

--- Train Dataset Sample ---
{'prompt': '<|im_start|>system\nYou are a helpful assistant. Please format your response as follows:\nApproach: <step-by-step reasoning>\nOutput: <final answer><|im_end|>\n<|im_start|>user\nGenerate lab result data in CSV format.<|im_end|>\n<|im_start|>assistant\n', 'chosen': 'Approach:\n1. Task: Create lab result in CSV\n2. Complexity: medium - 5-8 fields, 2-3 levels\n3. Format rules: header row, comma-separated, quoted fields with commas\n4. Structure: Organize data logically with appropriate nesting\n5. Populate fields with realistic example data based on the schema.\n\nOutput:\norder_date,panel,patient_mrn,result_id,results\r\n2026-01-01,CBC,MRN-595201,LAB-6843976,"[{""test"": ""Glucose"", ""value"": 112.1, ""unit"": ""mg/dL"", ""flag"": ""high""}, {""test"": ""WBC"", ""value"": 108."\r\n2026-01-13,Lipid,MRN-841114,LAB-2871982,"[{""test"": ""WBC"", ""value"": 159.6, ""unit"": ""g/dL"", ""flag"": ""high""}, {""test"": ""Glucose"", ""value"": 169.1"\r\n2026-01-06,Lipid,MRN-882965,LAB-2096703,"[{""test"": ""Glucose"", ""value"": 155.0, ""unit"": ""g/dL"", ""flag"": ""high""}, {""test"": ""WBC"", ""value"": 184.4"\r\n', 'rejected': 'Approach:  \n1. Understand the request: The user wants lab result data in CSV format. Since no specific details (e.g., patient names, test types, values, units, dates) were provided, I will generate a generic, realistic set of lab result data.  \n2. Structure the data: A typical lab result CSV includes columns such as Patient ID, Test Name, Result Value, Units, Reference Range, and Date.  \n3. Generate realistic sample data: Create 10 sample entries with plausible values (e.g., blood glucose, cholesterol, white blood cell count) and realistic reference ranges.  \n4. Format the data properly: Ensure the CSV is properly formatted with a header row and each field separated by commas.  \n5. Output the result: Present the CSV data in a clean, readable format that can be saved as a .csv file.  \n\nOutput:  \nPatientID,TestName,ResultValue,Units,ReferenceRange,Date  \n1001,"Blood Glucose",102,"mg/dL","70-100",2023-10-05  \n1002,"Total Cholesterol",210,"mg/dL","125-200",2023-10-05  \n1003,"Hemoglobin A1c",5.8,"%", "4.0-5.6",2023-10-05  \n1004,"White Blood Cell Count",7.2,"k/μL","4.5-11.0",2023-10-05  \n1005,"Creatinine",0.9,"mg/dL","0.7-1.3",2023-10-05  \n1006,"Sodium",140,"mEq/L","135-145",2023-10-06  \n1007,"Potassium",4.2,"mEq/L","3.5-5.0",2023-10-06  \n1008,"BUN",18,"mg/dL","7-20",2023-10-06  \n1009,"Liver Enzyme (ALT)",35,"U/L","0-40",2023-10-07  \n1010,"HDL Cholesterol",50,"mg/dL","35-60",2023-10-07'}

Train size: 160, Eval size: 160

In [ ]:
# データを分割する (90% を学習に、10% を評価に)
split_dataset = special_dpo_dataset.train_test_split(test_size=0.1, seed=3407)

train_dataset = split_dataset["train"]
eval_dataset = split_dataset["test"]

print(f"📊 分割完了！")
print(f"学習用 (train_dataset): {len(train_dataset)} 件")
print(f"評価用 (eval_dataset) : {len(eval_dataset)} 件")

In [ ]:
from google.colab import userdata
HF_TOKEN = userdata.get('HF_TOKEN2')

In [ ]:

# -----------------------------
# 1) HF login (once)
# -----------------------------
# HF Hub上のデータセットを読むため、HuggingFaceにログインします。
#
from huggingface_hub import login
login(HF_TOKEN)  # Colab will prompt

### SFTモデルのロード＆学習

In [ ]:
from unsloth import FastLanguageModel, PatchDPOTrainer
import torch
from peft import set_peft_model_state_dict
from huggingface_hub import hf_hub_download
from safetensors.torch import load_file
from trl import DPOConfig, DPOTrainer

# --- 1. 事前パッチ ---
PatchDPOTrainer()

# --- 2. モデルロード ---
base_model_id = "Qwen/Qwen3-4B-Instruct-2507"
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = base_model_id,
    max_seq_length = 2048,
    load_in_4bit = True,
    trust_remote_code = True,
)

# --- 3. LoRA層の追加 (r=16に固定) ---
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
)

# --- 4. 0.73の重みを注入 (外科手術) ---
print("🔄 0.73の重みを注入中...")
adapter_weights = hf_hub_download(repo_id="satoyutaka/llm2025_main_0", filename="adapter_model.safetensors")
state_dict = load_file(adapter_weights)
set_peft_model_state_dict(model, state_dict)

# --- 5. DPO学習の設定 (極限まで負荷を下げる) ---
dpo_trainer = DPOTrainer(
    model = model,
    ref_model = None, # メモリ節約
    args = DPOConfig(
        per_device_train_batch_size = 1, # T4の限界に挑む
        gradient_accumulation_steps = 8,
        warmup_ratio = 0.1,
        num_train_epochs = 3,
        learning_rate = 5e-6,
        fp16 = True,
        bf16 = False, # T4はFalse
        logging_steps = 1,
        optim = "adamw_8bit",
        output_dir = "outputs",
        beta = 0.1,
        report_to = "none",
        remove_unused_columns = False, # これを追加すると安定することがあるよ
    ),
    train_dataset = train_dataset,
    eval_dataset = eval_dataset,
    tokenizer = tokenizer,
    max_length = 1024,
    max_prompt_length = 512,
)

print("🚀 さあ、今度こそ学習開始！")
dpo_trainer.train()

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

/usr/local/lib/python3.12/dist-packages/torchao/quantization/quant_api.py:2525: SyntaxWarning: invalid escape sequence '\.'
  * regex for parameter names, must start with `re:`, e.g. `re:language\.layers\..+\.q_proj.weight`.

🦥 Unsloth Zoo will now patch everything to make training faster!
Unsloth: WARNING `trust_remote_code` is True.
Are you certain you want to do remote code execution?
==((====))==  Unsloth 2025.12.7: Fast Qwen3 patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/3.55G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/237 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/707 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

Unsloth 2025.12.7 patched 36 layers with 36 QKV layers, 36 O layers and 36 MLP layers.

🔄 0.73の重みを注入中...

adapter_model.safetensors:   0%|          | 0.00/23.6M [00:00<?, ?B/s]

Extracting prompt in train dataset (num_proc=6):   0%|          | 0/160 [00:00<?, ? examples/s]

Applying chat template to train dataset (num_proc=6):   0%|          | 0/160 [00:00<?, ? examples/s]

Tokenizing train dataset (num_proc=6):   0%|          | 0/160 [00:00<?, ? examples/s]

Extracting prompt in eval dataset (num_proc=6):   0%|          | 0/160 [00:00<?, ? examples/s]

Applying chat template to eval dataset (num_proc=6):   0%|          | 0/160 [00:00<?, ? examples/s]

Tokenizing eval dataset (num_proc=6):   0%|          | 0/160 [00:00<?, ? examples/s]

🚀 さあ、今度こそ学習開始！

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 160 | Num Epochs = 3 | Total steps = 60
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 8 x 1) = 8
 "-____-"     Trainable parameters = 33,030,144 of 4,055,498,240 (0.81% trained)

Unsloth: Will smartly offload gradients to save VRAM!

TrainOutput(global_step=60, training_loss=0.05530330327386158, metrics={'train_runtime': 1150.1067, 'train_samples_per_second': 0.417, 'train_steps_per_second': 0.052, 'total_flos': 0.0, 'train_loss': 0.05530330327386158, 'epoch': 3.0})

In [ ]:
# from unsloth import FastLanguageModel
# import torch
# from peft import set_peft_model_state_dict
# from huggingface_hub import hf_hub_download
# from safetensors.torch import load_file

# # 1. ベースモデルのロード
# base_model_id = "QwAen/Qwen3-4B-Instruct-2507"
# model, tokenizer = FastLanguageModel.from_pretrained(
#     model_name = base_model_id,
#     max_seq_length = 2048,
#     load_in_4bit = True,
#     trust_remote_code = True,
# )

# # 2. DPO用のLoRA層を定義
# # 【重要】0.73アダプターと同じ r=16, lora_alpha=16 に設定します
# model = FastLanguageModel.get_peft_model(
#     model,
#     r = 16,  # ここを16に修正！
#     target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
#     lora_alpha = 16, # alphaもrと同じにするのが一般的だよ
#     lora_dropout = 0,
#     bias = "none",
#     use_gradient_checkpointing = "unsloth",
#     random_state = 3407,
# )

# # 3. 0.73の重みを強引に流し込む（外科手術パート）
# print("🔄 0.73の重みをダウンロードして適用中...")
# adapter_weights = hf_hub_download(repo_id="satoyutaka/llm2025_main_0", filename="adapter_model.safetensors")

# # 重みファイルをロード
# state_dict = load_file(adapter_weights)

# # 重みを現在のモデル（r=16になったモデル）に注入
# # これでサイズが一致するのでエラーが出なくなります
# set_peft_model_state_dict(model, state_dict)

# print("✅ ついに地獄脱出！！ 0.73の能力(r=16)を注入してDPOの準備が完了したよ！")

Unsloth: WARNING `trust_remote_code` is True.
Are you certain you want to do remote code execution?
==((====))==  Unsloth 2025.12.7: Fast Qwen3 patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
🔄 0.73の重みをダウンロードして適用中...
✅ ついに地獄脱出！！ 0.73の能力(r=16)を注入してDPOの準備が完了したよ！

In [ ]:
from google.colab import userdata
userdata.get('secretName')

In [ ]:
# # 16bitで結合して保存（これが一番精度が落ちにくい）
# new_model_name = "/content/drive/MyDrive/LLM2026/main_competition/DPO/struct-eval-comp-dpo-final"
# path = "/content/drive/MyDrive/LLM2026/main_competition/DPO/"


# # ローカルに保存する場合
# model.save_pretrained_merged(new_model_name, tokenizer, save_method = "merged_16bit")

# # Hugging Faceに直接アップロードする場合（推奨）
# model.push_to_hub_merged(
#     f"your-username/{new_model_name}",
#     tokenizer,
#     save_method = "merged_16bit",
#     token = "your_hf_token"
# )

In [ ]:
import os

# 1. 保存パスの設定（struct-eval-comp プロジェクト用）
adapter_name = "struct-eval-comp-dpo-v1"
drive_save_path = f"/content/drive/MyDrive/LLM2026/main_competition/DPO/{adapter_name}"
hf_model_id = f"satoyutaka/{adapter_name}" # 自分のHFユーザー名に合わせてね

# 2. Google ドライブへ保存
print(f"💾 Googleドライブに保存中: {drive_save_path}")
os.makedirs(drive_save_path, exist_ok=True)
model.save_pretrained(drive_save_path)
tokenizer.save_pretrained(drive_save_path)

# 3. Hugging Face へアップロード
print(f"🚀 Hugging Faceにアップロード中: {hf_model_id}")
try:
    model.push_to_hub(hf_model_id)
    tokenizer.push_to_hub(hf_model_id)
    print("✅ HFへのアップロードも完了したよ！")
except Exception as e:
    print(f"⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: {e}")

print("\n✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！")

💾 Googleドライブに保存中: /content/drive/MyDrive/LLM2026/main_competition/DPO/struct-eval-comp-dpo-v1
🚀 Hugging Faceにアップロード中: satoyutaka/struct-eval-comp-dpo-v1
⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: (Request ID: Root=1-6983e6bc-3ebdc2933a5f5fa7338bb3c6;6eee2338-7315-4cfd-9edc-703f3a03373d)

403 Forbidden: You don't have the rights to create a model under the namespace "satoyutaka".
Cannot access content at: https://huggingface.co/api/repos/create.
Make sure your token has the correct permissions.

✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！

### 推論してチェック

In [ ]:
from unsloth import FastLanguageModel
import torch

# 1. パスの設定
adapter_path = "/content/drive/MyDrive/LLM2026/main_competition/DPO/struct-eval-comp-dpo-v1"
merged_save_path = "/content/drive/MyDrive/LLM2026/main_competition/DPO/merged_model"

# 2. モデルとアダプターのロード
# ※DPO学習時と同じ設定でロードします
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = adapter_path, # ドライブのアダプターパス
    max_seq_length = 2048,
    load_in_4bit = True,       # 4bitでロード
    trust_remote_code = True,
)

# 3. 結合（Merge）して保存
# save_pretrained_merged を使うと、Unslothが綺麗に統合してくれます
print("🔄 ベースモデルとアダプターを結合中...（これには数分かかります）")

model.save_pretrained_merged(
    merged_save_path,
    tokenizer,
    save_method = "merged_16bit", # 精度を保つために16bitで結合
)

print(f"✅ 結合完了！保存先: {merged_save_path}")

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

/usr/local/lib/python3.12/dist-packages/torchao/quantization/quant_api.py:2525: SyntaxWarning: invalid escape sequence '\.'
  * regex for parameter names, must start with `re:`, e.g. `re:language\.layers\..+\.q_proj.weight`.

🦥 Unsloth Zoo will now patch everything to make training faster!
Unsloth: WARNING `trust_remote_code` is True.
Are you certain you want to do remote code execution?
==((====))==  Unsloth 2025.12.7: Fast Qwen3 patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/3.55G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/237 [00:00<?, ?B/s]

Unsloth 2025.12.7 patched 36 layers with 36 QKV layers, 36 O layers and 36 MLP layers.

🔄 ベースモデルとアダプターを結合中...（これには数分かかります）

config.json: 0.00B [00:00, ?B/s]

Found HuggingFace hub cache directory: /root/.cache/huggingface/hub

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Checking cache directory for required files...
Cache check failed: model-00001-of-00002.safetensors not found in local cache.
Not all required files found in cache. Will proceed with downloading.
Checking cache directory for required files...
Cache check failed: tokenizer.model not found in local cache.
Not all required files found in cache. Will proceed with downloading.

Unsloth: Preparing safetensor model files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

Unsloth: Preparing safetensor model files:  50%|█████     | 1/2 [00:45<00:45, 45.43s/it]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.08G [00:00<?, ?B/s]

Unsloth: Preparing safetensor model files: 100%|██████████| 2/2 [01:22<00:00, 41.47s/it]

Note: tokenizer.model not found (this is OK for non-SentencePiece models)

Unsloth: Merging weights into 16bit: 100%|██████████| 2/2 [02:54<00:00, 87.41s/it]

Unsloth: Merge process complete. Saved to `/content/drive/MyDrive/LLM2026/main_competition/DPO/merged_model`
✅ 結合完了！保存先: /content/drive/MyDrive/LLM2026/main_competition/DPO/merged_model

In [ ]:
import json
from tqdm import tqdm
from unsloth import FastLanguageModel

# 1. 推論モードの設定（すでにロード済みならスキップOK）
FastLanguageModel.for_inference(model)

def evaluate_model(test_dataset):
    correct_content = 0
    perfect_format = 0
    total = len(test_dataset)

    print(f"🧐 {total}件のデータで検証開始...")

    for i in tqdm(range(total)):
        item = test_dataset[i]
        prompt_input = item["prompt"]  # DPOデータセット作成時のキー名に合わせてね
        ground_truth = item["chosen"]  # 正解データ

        # モデル推論
        inputs = tokenizer([prompt_input], return_tensors = "pt").to("cuda")
        outputs = model.generate(**inputs, max_new_tokens = 512, do_sample = False)
        prediction = tokenizer.decode(outputs[0], skip_special_tokens=True)

        # 回答部分のみ抽出（学習時の区切り文字に合わせて調整してね）
        response = prediction.split("### Response:\n")[-1].strip()

        # --- 評価1: フォーマットチェック ---
        # Markdownの ```json や 挨拶が入っていないか
        is_clean_json = response.startswith("{") and response.endswith("}") and "```" not in response
        if is_clean_json:
            perfect_format += 1

        # --- 評価2: 内容のチェック ---
        # ここでは単純比較。必要に応じてJSONの中身を取り出して比較してね
        if response == ground_truth:
            correct_content += 1
        else:
            # 失敗例を1つだけ表示（デバッグ用）
            if i == 0:
                print(f"\n[Diff Example]\nExpected: {ground_truth}\nGot: {response}")

    # スコア算出
    format_rate = (perfect_format / total) * 100
    accuracy_rate = (correct_content / total) * 100

    print("\n" + "="*30)
    print(f"🏆 検証結果 (Project: struct-eval-comp)")
    print(f"フォーマット遵守率: {format_rate:.2f}%")
    print(f"内容一致率（正解率）: {accuracy_rate:.2f}%")
    print("="*30)

# 実行！
evaluate_model(eval_dataset)

🧐 160件のデータで検証開始...

  1%|          | 1/160 [01:27<3:51:33, 87.38s/it]

[Diff Example]
Expected: Approach:
1. Task: Create lab result in CSV
2. Complexity: medium - 5-8 fields, 2-3 levels
3. Format rules: header row, comma-separated, quoted fields with commas
4. Structure: Organize data logically with appropriate nesting
5. Populate fields with realistic example data based on the schema.

Output:
order_date,panel,patient_mrn,result_id,results
2026-01-01,CBC,MRN-595201,LAB-6843976,"[{""test"": ""Glucose"", ""value"": 112.1, ""unit"": ""mg/dL"", ""flag"": ""high""}, {""test"": ""WBC"", ""value"": 108."
2026-01-13,Lipid,MRN-841114,LAB-2871982,"[{""test"": ""WBC"", ""value"": 159.6, ""unit"": ""g/dL"", ""flag"": ""high""}, {""test"": ""Glucose"", ""value"": 169.1"
2026-01-06,Lipid,MRN-882965,LAB-2096703,"[{""test"": ""Glucose"", ""value"": 155.0, ""unit"": ""g/dL"", ""flag"": ""high""}, {""test"": ""WBC"", ""value"": 184.4"

Got: system
You are a helpful assistant. Please format your response as follows:
Approach: <step-by-step reasoning>
Output: <final answer>
user
Generate lab result data in CSV format.
assistant
Approach:
To generate lab result data in CSV format, I will create a structured dataset with realistic lab values across common test categories (e.g., blood count, chemistry, glucose, electrolytes). Each row will represent a patient's lab result with fields such as patient ID, test name, value, units, and date. I will ensure the data is diverse, plausible, and formatted correctly for CSV import. The output will be a clean, tab-separated string with headers, suitable for use in spreadsheets or databases.

Output:
```csv
PatientID,TestName,Value,Units,Date
P001,Blood Glucose,98.5,mg/dL,2023-10-01
P001,White Blood Cells,7.2,thousands/µL,2023-10-01
P001,Hemoglobin,14.2,g/dL,2023-10-01
P001,Platelets,220,thousands/µL,2023-10-01
P001,Sodium,142,mEq/L,2023-10-01
P001,Potassium,4.1,mEq/L,2023-10-01
P001,Creatinine,0.8,mg/dL,2023-10-01
P002,Blood Glucose,112.3,mg/dL,2023-10-02
P002,White Blood Cells,6.8,thousands/µL,2023-10-02
P002,Hemoglobin,13.5,g/dL,2023-10-02
P002,Platelets,185,thousands/µL,2023-10-02
P002,Sodium,138,mEq/L,2023-10-02
P002,Potassium,3.9,mEq/L,2023-10-02
P002,Creatinine,0.9,mg/dL,2023-10-02
P

100%|██████████| 160/160 [1:15:53<00:00, 28.46s/it]

==============================
🏆 検証結果 (Project: struct-eval-comp)
フォーマット遵守率: 0.00%
内容一致率（正解率）: 0.00%
==============================

# DPO２回目

## データのロード

In [ ]:
from datasets import load_dataset

# 1. 保存したjsonlファイルを読み込む
# 先ほどのスクリプトと同じディレクトリにあることを想定しているよ
data_files = {
    "train": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/struct_special_dpo_train.jsonl",
    "eval": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/struct_special_dpo_eval.jsonl"
}

# json形式でロード
dataset = load_dataset("json", data_files=data_files)

# 2. train と eval に切り分け
train_dataset = dataset["train"]
eval_dataset = dataset["eval"]

# 3. 中身の確認（デバッグ用：最初の1件を表示）
print("--- Train Dataset Sample ---")
print(train_dataset[0])
print(f"\nTrain size: {len(train_dataset)}, Eval size: {len(eval_dataset)}")

Generating train split: 0 examples [00:00, ? examples/s]

Generating eval split: 0 examples [00:00, ? examples/s]

--- Train Dataset Sample ---
{'prompt': '### Instruction:\n<|im_start|>system\nYou are a helpful assistant. Please format your response as follows:\nApproach: <step-by-step reasoning>\nOutput: <final answer><|im_end|>\n<|im_start|>user\nOutput news article as TOML.<|im_end|>\n<|im_start|>assistant\n\n\n### Response:\n', 'chosen': 'Approach:\n1. Task: Create news article in TOML\n2. Complexity: complex - 8-10 fields, 3-4 levels\n3. Format rules: key=value syntax, [sections], proper types\n4. Structure: Organize data logically with appropriate nesting\n5. Populate fields with realistic example data based on the schema.\n\nOutput:\narticle_id = "ART-5766974"\nheadline = "Decentralized maximized challenge"\nauthor = "Dr. Eric Miller MD"\npublished = "2026-01-04T16:46:57.191248"\nsection = "Business"\ncontent = "Western experience subject current contain whether. Sell college camera amount none. Outside experience somebody.\\nRead challenge go degree almost. Place number language positive serve part high."\ntags = [ "wall", "reality", "while", "company", "every",]\nviews = 66879\nshares = 3461', 'rejected': 'Approach:  \n1. Understand the request: The user wants a news article formatted in TOML (Tom\'s Obvious, Minimal Language), a configuration file format.  \n2. Recognize that TOML is not designed for rich content like news articles, which typically use Markdown or HTML. However, it can represent structured data.  \n3. Create a minimal, structured news article in TOML that includes essential fields such as title, author, date, and content.  \n4. Ensure the format adheres to TOML syntax (key-value pairs, tables, comments, etc.) and remains readable and meaningful.  \n5. Avoid markdown or HTML because TOML does not support them natively. Instead, represent the article content in plain text or simple lines.  \n\nOutput:  \n```toml\n# News Article in TOML Format\n\n[[article]]\ntitle = "Global Climate Summit Concludes with Historic Agreement"\nauthor = "Elena Martinez"\ndate = "2024-04-15"\nlocation = "Copenhagen, Denmark"\ncategory = "Environment"\n\ncontent = """\nWorld leaders from 195 nations have reached a landmark agreement to limit global temperature rise to 1.5°C above pre-industrial levels. The deal, known as the Copenhagen Accord 2024, includes binding targets for carbon emissions reduction, increased funding for climate resilience in developing countries, and a global transition to renewable energy by 2035.\n\nKey highlights include:\n- A commitment to reduce greenhouse gas emissions by 45% by 2030.\n- A pledge to mobilize $100 billion annually in climate finance for vulnerable nations.\n- The establishment of a new international climate monitoring body.\n\nThe summit, attended by heads of state, scientists, and civil society leaders, marked the most significant progress in climate policy since the 1992 Earth Summit.\n\nCritics have raised concerns about enforcement mechanisms and equity, while environmental groups welcomed the agreement as a critical step toward planetary survival.\n"""\n\nsource = "Global Environmental Network"\ntags = ["climate", "environment", "agreement", "renewables"]\n```', 'strategy': 'model_generated'}

Train size: 225, Eval size: 25

## モデルのロード＆学習

1. beta を下げる (0.1 → 0.05)

beta は、モデルが「どれだけ正解と不正解の差を重く見るか」の指標。値を小さくすると、今回のような「Markdownがついている（rejected）」ことに対して、より厳しい罰則を与えるようになる。

2. learning_rate を下げる (5e-6 → 2e-6)

0.73（または0.76）の重みを注入して「追加」で学習する場合、学習率が高いとせっかく積み上げた推論力が壊れちゃう（破滅的忘却）ことがある。お作法だけを優しく教え込むために、少し低めに設定。

3. dataset の指定

さっきフォルダに保存した「抽出データ（JSON/CSV特化）」を読み込んで、datasetに渡す。

In [ ]:
from unsloth import FastLanguageModel, PatchDPOTrainer
import torch
from peft import set_peft_model_state_dict
from huggingface_hub import hf_hub_download
from safetensors.torch import load_file
from trl import DPOConfig, DPOTrainer

# --- 1. 事前パッチ ---
PatchDPOTrainer()

# --- 2. モデルロード ---
base_model_id = "Qwen/Qwen3-4B-Instruct-2507"
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = base_model_id,
    max_seq_length = 2048,
    load_in_4bit = True,
    trust_remote_code = True,
)

# --- 3. LoRA層の追加 (r=16に固定) ---
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
)

# --- 4. 0.73の重みを注入 (外科手術) ---
print("🔄 0.73の重みを注入中...")
adapter_weights = hf_hub_download(repo_id="satoyutaka/LLM2025_main_DPO", filename="adapter_model.safetensors")
state_dict = load_file(adapter_weights)
set_peft_model_state_dict(model, state_dict)

# --- 5. DPO学習の設定 (極限まで負荷を下げる) ---
dpo_trainer = DPOTrainer(
    model = model,
    ref_model = None, # メモリ節約
    args = DPOConfig(
        per_device_train_batch_size = 1, # T4の限界に挑む
        gradient_accumulation_steps = 8,
        warmup_ratio = 0.1,
        num_train_epochs = 3,
        learning_rate = 2e-6,
        fp16 = True,
        bf16 = False, # T4はFalse
        logging_steps = 1,
        optim = "adamw_8bit",
        output_dir = "outputs",
        beta = 0.05,
        report_to = "none",
        remove_unused_columns = False, # これを追加すると安定することがあるよ
    ),
    train_dataset = train_dataset,
    eval_dataset = eval_dataset,
    tokenizer = tokenizer,
    max_length = 1024,
    max_prompt_length = 512,
)

print("🚀 さあ、学習開始！")
dpo_trainer.train()

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

/usr/local/lib/python3.12/dist-packages/torchao/quantization/quant_api.py:2525: SyntaxWarning: invalid escape sequence '\.'
  * regex for parameter names, must start with `re:`, e.g. `re:language\.layers\..+\.q_proj.weight`.

🦥 Unsloth Zoo will now patch everything to make training faster!
Unsloth: WARNING `trust_remote_code` is True.
Are you certain you want to do remote code execution?
==((====))==  Unsloth 2025.12.7: Fast Qwen3 patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/3.55G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/237 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/707 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

Unsloth 2025.12.7 patched 36 layers with 36 QKV layers, 36 O layers and 36 MLP layers.

🔄 0.73の重みを注入中...

adapter_model.safetensors:   0%|          | 0.00/132M [00:00<?, ?B/s]

Extracting prompt in train dataset (num_proc=6):   0%|          | 0/225 [00:00<?, ? examples/s]

Applying chat template to train dataset (num_proc=6):   0%|          | 0/225 [00:00<?, ? examples/s]

Tokenizing train dataset (num_proc=6):   0%|          | 0/225 [00:00<?, ? examples/s]

Extracting prompt in eval dataset (num_proc=6):   0%|          | 0/25 [00:00<?, ? examples/s]

Applying chat template to eval dataset (num_proc=6):   0%|          | 0/25 [00:00<?, ? examples/s]

Tokenizing eval dataset (num_proc=6):   0%|          | 0/25 [00:00<?, ? examples/s]

🚀 さあ、学習開始！

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 225 | Num Epochs = 3 | Total steps = 87
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 8 x 1) = 8
 "-____-"     Trainable parameters = 33,030,144 of 4,055,498,240 (0.81% trained)

Unsloth: Will smartly offload gradients to save VRAM!

TrainOutput(global_step=87, training_loss=0.018866628156867862, metrics={'train_runtime': 1752.8522, 'train_samples_per_second': 0.385, 'train_steps_per_second': 0.05, 'total_flos': 0.0, 'train_loss': 0.018866628156867862, 'epoch': 3.0})

## モデルの保存

In [ ]:
import os

# 1. 保存パスの設定（struct-eval-comp プロジェクト用）
adapter_name = "struct-eval-comp-dpo-v2"
drive_save_path = f"/content/drive/MyDrive/LLM2026/main_competition/DPO/{adapter_name}"
hf_model_id = "satoyutaka/LLM2025_main_0_DPO2" # 自分のHFユーザー名に合わせてね

# 2. Google ドライブへ保存
print(f"💾 Googleドライブに保存中: {drive_save_path}")
os.makedirs(drive_save_path, exist_ok=True)
model.save_pretrained(drive_save_path)
tokenizer.save_pretrained(drive_save_path)

# 3. Hugging Face へアップロード
print(f"🚀 Hugging Faceにアップロード中: {hf_model_id}")
try:
    model.push_to_hub(hf_model_id)
    tokenizer.push_to_hub(hf_model_id)
    print("✅ HFへのアップロードも完了したよ！")
except Exception as e:
    print(f"⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: {e}")

print("\n✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！")

💾 Googleドライブに保存中: /content/drive/MyDrive/LLM2026/main_competition/DPO/struct-eval-comp-dpo-v2
🚀 Hugging Faceにアップロード中: satoyutaka/LLM2025_main_0_DPO2
⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: (Request ID: Root=1-69851889-0c51bdd709ab70524878221d;a26a7f23-fad8-42f6-b606-baa0866077a4)

403 Forbidden: Forbidden: you must use a write token to upload to a repository..
Cannot access content at: https://huggingface.co/api/models/satoyutaka/LLM2025_main_0_DPO2/preupload/main.
Make sure your token has the correct permissions.

✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！

# 3回目

## データのロード

In [ ]:
from datasets import load_dataset

# 1. 保存したjsonlファイルを読み込む
# 先ほどのスクリプトと同じディレクトリにあることを想定しているよ
data_files = {
    "train": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/struct_special_2_dpo_train.jsonl",
    "eval": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/struct_special_2_dpo_eval.jsonl"
}

# json形式でロード
dataset = load_dataset("json", data_files=data_files)

# 2. train と eval に切り分け
train_dataset = dataset["train"]
eval_dataset = dataset["eval"]

# 3. 中身の確認（デバッグ用：最初の1件を表示）
print("--- Train Dataset Sample ---")
print(train_dataset[0])
print(f"\nTrain size: {len(train_dataset)}, Eval size: {len(eval_dataset)}")

--- Train Dataset Sample ---
{'prompt': '### Instruction:\n<|im_start|>system\nYou are a helpful assistant. Please format your response as follows:\nApproach: <step-by-step reasoning>\nOutput: <final answer><|im_end|>\n<|im_start|>user\nOutput news article as TOML.<|im_end|>\n<|im_start|>assistant\n\n\n### Response:\n', 'chosen': 'article_id = "ART-5766974"\nheadline = "Decentralized maximized challenge"\nauthor = "Dr. Eric Miller MD"\npublished = "2026-01-04T16:46:57.191248"\nsection = "Business"\ncontent = "Western experience subject current contain whether. Sell college camera amount none. Outside experience somebody.\\nRead challenge go degree almost. Place number language positive serve part high."\ntags = [ "wall", "reality", "while", "company", "every",]\nviews = 66879\nshares = 3461', 'rejected': 'Approach:  \n1. Understand the request: The user wants a news article formatted in TOML (Tom\'s Obvious, Minimal Language), a configuration file format.  \n2. Recognize that TOML is not designed for rich content like news articles, which typically use Markdown or HTML. However, it can represent structured data.  \n3. Create a minimal, structured news article in TOML that includes essential fields such as title, author, date, and content.  \n4. Ensure the format adheres to TOML syntax (key-value pairs, tables, comments, etc.) and remains readable and meaningful.  \n5. Avoid markdown or HTML because TOML does not support them natively. Instead, represent the article content in plain text or simple lines.  \n\nOutput:  \n```toml\n# News Article in TOML Format\n\n[[article]]\ntitle = "Global Climate Summit Concludes with Historic Agreement"\nauthor = "Elena Martinez"\ndate = "2024-04-15"\nlocation = "Copenhagen, Denmark"\ncategory = "Environment"\n\ncontent = """\nWorld leaders from 195 nations have reached a landmark agreement to limit global temperature rise to 1.5°C above pre-industrial levels. The deal, known as the Copenhagen Accord 2024, includes binding targets for carbon emissions reduction, increased funding for climate resilience in developing countries, and a global transition to renewable energy by 2035.\n\nKey highlights include:\n- A commitment to reduce greenhouse gas emissions by 45% by 2030.\n- A pledge to mobilize $100 billion annually in climate finance for vulnerable nations.\n- The establishment of a new international climate monitoring body.\n\nThe summit, attended by heads of state, scientists, and civil society leaders, marked the most significant progress in climate policy since the 1992 Earth Summit.\n\nCritics have raised concerns about enforcement mechanisms and equity, while environmental groups welcomed the agreement as a critical step toward planetary survival.\n"""\n\nsource = "Global Environmental Network"\ntags = ["climate", "environment", "agreement", "renewables"]\n```', 'strategy': 'model_generated'}

Train size: 225, Eval size: 25

## モデルのロードおよび学習

In [ ]:
from unsloth import FastLanguageModel, PatchDPOTrainer
import torch
from peft import set_peft_model_state_dict
from huggingface_hub import hf_hub_download
from safetensors.torch import load_file
from trl import DPOConfig, DPOTrainer

# --- 1. 事前パッチ ---
PatchDPOTrainer()

# --- 2. モデルロード ---
base_model_id = "Qwen/Qwen3-4B-Instruct-2507"
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = base_model_id,
    max_seq_length = 2048,
    load_in_4bit = True,
    trust_remote_code = True,
)

# --- 3. LoRA層の追加 (r=16に固定) ---
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
)

# --- 4. 0.766の重みを注入 (外科手術) ---
print("🔄 0.766の重みを注入中...")
adapter_weights = hf_hub_download(repo_id="satoyutaka/LLM2025_main_0_DPO2", filename="adapter_model.safetensors")
state_dict = load_file(adapter_weights)
set_peft_model_state_dict(model, state_dict)

# --- 5. DPO学習の設定 (極限まで負荷を下げる) ---
dpo_trainer = DPOTrainer(
    model = model,
    ref_model = None, # メモリ節約
    args = DPOConfig(
        per_device_train_batch_size = 1, # T4の限界に挑む
        gradient_accumulation_steps = 8,
        warmup_ratio = 0.1,
        num_train_epochs = 3,
        learning_rate = 2e-6,
        fp16 = True,
        bf16 = False, # T4はFalse
        logging_steps = 1,
        optim = "adamw_8bit",
        output_dir = "outputs",
        beta = 0.05,
        report_to = "none",
        remove_unused_columns = False, # これを追加すると安定することがあるよ
    ),
    train_dataset = train_dataset,
    eval_dataset = eval_dataset,
    tokenizer = tokenizer,
    max_length = 1024,
    max_prompt_length = 512,
)

print("🚀 さあ、学習開始！")
dpo_trainer.train()

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
Unsloth: WARNING `trust_remote_code` is True.
Are you certain you want to do remote code execution?
==((====))==  Unsloth 2026.1.4: Fast Qwen3 patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/3.55G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/237 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/707 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

Unsloth 2026.1.4 patched 36 layers with 36 QKV layers, 36 O layers and 36 MLP layers.

🔄 0.766の重みを注入中...

adapter_model.safetensors:   0%|          | 0.00/132M [00:00<?, ?B/s]

Extracting prompt in train dataset (num_proc=4):   0%|          | 0/225 [00:00<?, ? examples/s]

Applying chat template to train dataset (num_proc=4):   0%|          | 0/225 [00:00<?, ? examples/s]

Tokenizing train dataset (num_proc=4):   0%|          | 0/225 [00:00<?, ? examples/s]

Extracting prompt in eval dataset (num_proc=4):   0%|          | 0/25 [00:00<?, ? examples/s]

Applying chat template to eval dataset (num_proc=4):   0%|          | 0/25 [00:00<?, ? examples/s]

Tokenizing eval dataset (num_proc=4):   0%|          | 0/25 [00:00<?, ? examples/s]

🚀 さあ、学習開始！

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 225 | Num Epochs = 3 | Total steps = 87
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 8 x 1) = 8
 "-____-"     Trainable parameters = 33,030,144 of 4,055,498,240 (0.81% trained)

Unsloth: Will smartly offload gradients to save VRAM!

TrainOutput(global_step=87, training_loss=0.018272562000643592, metrics={'train_runtime': 1653.0606, 'train_samples_per_second': 0.408, 'train_steps_per_second': 0.053, 'total_flos': 0.0, 'train_loss': 0.018272562000643592, 'epoch': 3.0})

## モデルの保存

In [ ]:
import os

# 1. 保存パスの設定（struct-eval-comp プロジェクト用）
adapter_name = "struct-eval-comp-dpo-v3"
drive_save_path = f"/content/drive/MyDrive/LLM2026/main_competition/DPO/{adapter_name}"
hf_model_id = "satoyutaka/LLM2025_main_0_DPO3" # 自分のHFユーザー名に合わせてね

# 2. Google ドライブへ保存
print(f"💾 Googleドライブに保存中: {drive_save_path}")
os.makedirs(drive_save_path, exist_ok=True)
model.save_pretrained(drive_save_path)
tokenizer.save_pretrained(drive_save_path)

# 3. Hugging Face へアップロード
print(f"🚀 Hugging Faceにアップロード中: {hf_model_id}")
try:
    model.push_to_hub(hf_model_id)
    tokenizer.push_to_hub(hf_model_id)
    print("✅ HFへのアップロードも完了したよ！")
except Exception as e:
    print(f"⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: {e}")

print("\n✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！")

💾 Googleドライブに保存中: /content/drive/MyDrive/LLM2026/main_competition/DPO/struct-eval-comp-dpo-v3
🚀 Hugging Faceにアップロード中: satoyutaka/LLM2025_main_0_DPO3
⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: (Request ID: Root=1-69856a0b-7649f4ef0017d1b804a68edc;c6b945e2-7af5-45ef-ac20-d687212657c8)

403 Forbidden: You don't have the rights to create a model under the namespace "satoyutaka".
Cannot access content at: https://huggingface.co/api/repos/create.
Make sure your token has the correct permissions.

✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！

# 4回目

🕵️‍♂️ 推論結果（0.77064）の分析レポート

ゆーちゃの読み通り、件数でおそらく30〜35件ほどミスをしている計算になるね。 でも、このミスの原因は「頭が悪いから（知識がないから）」じゃない。**「お行儀が悪いから」**だ！

ファイルの冒頭（p_7b33... のタスク）を見てみて：

JSON
"generation": "```json\n{\n  \"ecosystem\": {\n    \"name\": ...\n  }\n}\n```"
まだ ```json（Markdown）が出ちゃってる！！！

評価システム（採点プログラム）は、おそらくこういう挙動をしているはずだよ：

Strict Mode: 「JSON形式で答えろ」と言ったのに、先頭に ``` がある？ → パースエラー（0点）

Loose Mode: もし多少許容する採点だとしても、余計な文字が含まれていると完全一致率が下がる。

CSVの方（Glimmerbeetleのタスク）は綺麗に ``` なしで出力できているね。だから点数が伸びて0.77までは行けたんだ。つまり、**「JSONの問題のときだけ、まだMarkdownの癖が抜けていない」**のが敗因だ！

🚀 0.8への確実な道：Markdown抹殺計画

0.77までは「思考をカット」して伸びた。 次は**「Markdown（```）を物理的に消滅させたデータ」**で学習させて、モデルに「バッククォートなんて文字は私の辞書にはない」と思わせる必要がある。

昨日提案しかけた**「Pro+版」をさらに強化した、「Markdown抹殺・最終決戦仕様」**のコードをここに用意したよ。

今夜のセットは、このコードでデータを作って、学習（できれば0.73のアダプタから再スタート）してみて！

## データのロード

In [ ]:
from datasets import load_dataset

# 1. 保存したjsonlファイルを読み込む
# 先ほどのスクリプトと同じディレクトリにあることを想定しているよ
data_files = {
    "train": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/struct_special_4_dpo_train.jsonl",
    "eval": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/struct_special_4_dpo_eval.jsonl"
}

# json形式でロード
dataset = load_dataset("json", data_files=data_files)

# 2. train と eval に切り分け
train_dataset = dataset["train"]
eval_dataset = dataset["eval"]

# 3. 中身の確認（デバッグ用：最初の1件を表示）
print("--- Train Dataset Sample ---")
print(train_dataset[0])
print(f"\nTrain size: {len(train_dataset)}, Eval size: {len(eval_dataset)}")

Generating train split: 0 examples [00:00, ? examples/s]

Generating eval split: 0 examples [00:00, ? examples/s]

--- Train Dataset Sample ---
{'prompt': '### Instruction:\n<|im_start|>system\nYou are a helpful assistant. Please format your response as follows:\nApproach: <step-by-step reasoning>\nOutput: <final answer><|im_end|>\n<|im_start|>user\nProduce a TOML document for a financial report.<|im_end|>\n<|im_start|>assistant\n\n\n### Response:\n', 'chosen': 'company = "Lee-Frank"\nticker = "PNOZ"\nquarter = "Q4 2020"\nrevenue = 95126242\nexpenses = 36470273\nnet_income = 18995645\neps = 2.94\n\n[metrics]\nprofit_margin = 20.94\nroe = 10.92', 'rejected': 'Approach:  \n1. Understand the requirements: The task is to create a TOML (Tom\'s Obvious, Minimal Language) document for a financial report. TOML is a simple, human-readable configuration format often used for storing configuration files or structured data.  \n2. Structure the financial report with logical sections: A typical financial report includes key sections such as metadata (e.g., report title, date, version), financial data (e.g., revenue, expenses, profit), and additional details (e.g., currency, period).  \n3. Use valid TOML syntax: Ensure proper use of keys, values, tables, and nested structures. Avoid invalid syntax like missing commas or incorrect indentation.  \n4. Choose realistic data: Use plausible financial values to represent a sample report.  \n5. Ensure clarity and readability: Organize the data in a way that is easy to parse and understand, both for humans and automated tools.\n\nOutput:  \n```toml\n[report]\ntitle = "Q3 2023 Financial Report"\ndate = "2023-09-30"\nversion = "1.0"\ncurrency = "USD"\n\n[financials]\nrevenue = 1500000\ncost_of_goods_sold = 750000\noperating_expenses = 300000\nnet_profit = 450000\n\n[summary]\ntotal_revenue = 1500000\ntotal_expenses = 1050000\nnet_income = 450000\n\n[metadata]\nsource = "Internal Accounting System"\nperiod = "Q3 2023"\nprepared_by = "Finance Department"\n```', 'strategy': 'model_generated'}

Train size: 225, Eval size: 25

## モデルのロードおよび学習

In [ ]:
from unsloth import FastLanguageModel, PatchDPOTrainer
import torch
from peft import set_peft_model_state_dict
from huggingface_hub import hf_hub_download
from safetensors.torch import load_file
from trl import DPOConfig, DPOTrainer

# --- 1. 事前パッチ ---
PatchDPOTrainer()

# --- 2. モデルロード ---
base_model_id = "Qwen/Qwen3-4B-Instruct-2507"
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = base_model_id,
    max_seq_length = 2048,
    load_in_4bit = True,
    trust_remote_code = True,
)

# --- 3. LoRA層の追加 (r=16に固定) ---
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
)

# --- 4. 0.766の重みを注入 (外科手術) ---
print("🔄 0.766の重みを注入中...")
adapter_weights = hf_hub_download(repo_id="satoyutaka/LLM2025_main_0", filename="adapter_model.safetensors")
state_dict = load_file(adapter_weights)
set_peft_model_state_dict(model, state_dict)

# --- 5. DPO学習の設定 (極限まで負荷を下げる) ---
dpo_trainer = DPOTrainer(
    model = model,
    ref_model = None, # メモリ節約
    args = DPOConfig(
        per_device_train_batch_size = 1, # T4の限界に挑む
        gradient_accumulation_steps = 8,
        warmup_ratio = 0.1,
        num_train_epochs = 3,
        learning_rate = 2e-6,
        fp16 = True,
        bf16 = False, # T4はFalse
        logging_steps = 1,
        optim = "adamw_8bit",
        output_dir = "outputs",
        beta = 0.05,
        report_to = "none",
        remove_unused_columns = False, # これを追加すると安定することがあるよ
    ),
    train_dataset = train_dataset,
    eval_dataset = eval_dataset,
    tokenizer = tokenizer,
    max_length = 1024,
    max_prompt_length = 512,
)

print("🚀 さあ、学習開始！")
dpo_trainer.train()

Unsloth: WARNING `trust_remote_code` is True.
Are you certain you want to do remote code execution?
==((====))==  Unsloth 2026.1.4: Fast Qwen3 patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
🔄 0.766の重みを注入中...

Extracting prompt in train dataset (num_proc=4):   0%|          | 0/225 [00:00<?, ? examples/s]

Applying chat template to train dataset (num_proc=4):   0%|          | 0/225 [00:00<?, ? examples/s]

Tokenizing train dataset (num_proc=4):   0%|          | 0/225 [00:00<?, ? examples/s]

Extracting prompt in eval dataset (num_proc=4):   0%|          | 0/25 [00:00<?, ? examples/s]

Applying chat template to eval dataset (num_proc=4):   0%|          | 0/25 [00:00<?, ? examples/s]

Tokenizing eval dataset (num_proc=4):   0%|          | 0/25 [00:00<?, ? examples/s]

🚀 さあ、学習開始！

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 225 | Num Epochs = 3 | Total steps = 87
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 8 x 1) = 8
 "-____-"     Trainable parameters = 33,030,144 of 4,055,498,240 (0.81% trained)

Unsloth: Will smartly offload gradients to save VRAM!

TrainOutput(global_step=87, training_loss=0.08182804721097152, metrics={'train_runtime': 1840.0739, 'train_samples_per_second': 0.367, 'train_steps_per_second': 0.047, 'total_flos': 0.0, 'train_loss': 0.08182804721097152, 'epoch': 3.0})

## モデルの保存

In [ ]:
import os

# 1. 保存パスの設定（struct-eval-comp プロジェクト用）
adapter_name = "struct-eval-comp-dpo-v4"
drive_save_path = f"/content/drive/MyDrive/LLM2026/main_competition/DPO/{adapter_name}"
hf_model_id = "satoyutaka/LLM2025_main_0_DPO4" # 自分のHFユーザー名に合わせてね

# 2. Google ドライブへ保存
print(f"💾 Googleドライブに保存中: {drive_save_path}")
os.makedirs(drive_save_path, exist_ok=True)
model.save_pretrained(drive_save_path)
tokenizer.save_pretrained(drive_save_path)

# 3. Hugging Face へアップロード
print(f"🚀 Hugging Faceにアップロード中: {hf_model_id}")
try:
    model.push_to_hub(hf_model_id)
    tokenizer.push_to_hub(hf_model_id)
    print("✅ HFへのアップロードも完了したよ！")
except Exception as e:
    print(f"⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: {e}")

print("\n✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！")

💾 Googleドライブに保存中: /content/drive/MyDrive/LLM2026/main_competition/DPO/struct-eval-comp-dpo-v4
🚀 Hugging Faceにアップロード中: satoyutaka/LLM2025_main_0_DPO4
⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: (Request ID: Root=1-6986642c-212a2b017a74c4a50da10be9;737739d0-85b9-4933-b0b9-9eed8246ef3b)

403 Forbidden: You don't have the rights to create a model under the namespace "satoyutaka".
Cannot access content at: https://huggingface.co/api/repos/create.
Make sure your token has the correct permissions.

✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！

# ５回目

🚀 struct-eval-comp: 第5回DPO学習メモ
📊 1. 使用データについて

「Markdown＆お喋り完全抹殺ドリル（Ver.5）」

構造化データ特化: JSON/CSV/YAMLなどの構造化タスクを重点的に強化（全体の約70%を配分）。

思考過程（CoT）の完全カット: Chosen（正解）から「Approach:」や「Output:」といったタグを物理的に排除し、純粋なデータのみを抽出。

Markdown＆不要解説の抹殺: 0.77モデルの弱点だった「```json」などのコードブロック記号や、末尾の「このデータは〜」といった余計な一言を、正規表現とトリミングで完全に消去。

対比学習: RejectedにあえてMarkdownやお喋りを残すことで、「余計なことを書くと減点」というルールをモデルに強く学習させる。

🤖 2. 学習モデルと外科手術

ベースモデル: Qwen3-4B-Instruct-2507

重み注入: 前回の最高スコア個体である 「0.77064モデル」 のアダプター重みを外科手術（set_peft_model_state_dict）でロード。

狙い: 0.77モデルが持つ「高い正解精度」を維持したまま、出力形式（お作法）だけを完璧に矯正する。

⚙️ 3. 学習パラメーター（スパルタ設定）

Learning Rate: 1e-6

すでに賢いモデルを壊さないよう、極めて低速で「お作法」だけを微調整。

Beta: 0.1 (または 0.15)

通常(0.05)より厳しめに設定。「お喋り」や「Markdown」を出した瞬間に報酬がガッツリ下がるスパルタ仕様。

Epochs: 3

250件の精選データに対し、3周かけて「無言でデータを出す」美学を叩き込む。

Gradient Accumulation: 16

T4 GPUのメモリ制限の中で、学習の安定性を最大化。

✨ 4. 期待される効果

パースエラーの解消: JSON出力時のバッククォートが消えることで、採点システムでの0点評価を回避。

完全一致率の向上: 文末の余計な解説文がなくなることで、構造化データの純度100%を実現。

大台突破: これまでの微増（0.766 → 0.77）から、お作法の改善による 「0.80超え」 へのジャンプアップを狙う。

## データのロード

In [ ]:
from datasets import load_dataset

# 1. 保存したjsonlファイルを読み込む
# 先ほどのスクリプトと同じディレクトリにあることを想定しているよ
data_files = {
    "train": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/struct_special_5_dpo_train.jsonl",
    "eval": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/struct_special_5_dpo_eval.jsonl"
}

# json形式でロード
dataset = load_dataset("json", data_files=data_files)

# 2. train と eval に切り分け
train_dataset = dataset["train"]
eval_dataset = dataset["eval"]

# 3. 中身の確認（デバッグ用：最初の1件を表示）
print("--- Train Dataset Sample ---")
print(train_dataset[0])
print(f"\nTrain size: {len(train_dataset)}, Eval size: {len(eval_dataset)}")

Generating train split: 0 examples [00:00, ? examples/s]

Generating eval split: 0 examples [00:00, ? examples/s]

--- Train Dataset Sample ---
{'prompt': '### Instruction:\n<|im_start|>system\nYou are a helpful assistant. Please format your response as follows:\nApproach: <step-by-step reasoning>\nOutput: <final answer><|im_end|>\n<|im_start|>user\nProduce a TOML document for a financial report.<|im_end|>\n<|im_start|>assistant\n\n\n### Response:\n', 'chosen': 'company = "Lee-Frank"\nticker = "PNOZ"\nquarter = "Q4 2020"\nrevenue = 95126242\nexpenses = 36470273\nnet_income = 18995645\neps = 2.94\n\n[metrics]\nprofit_margin = 20.94\nroe = 10.92', 'rejected': 'Approach:  \n1. Understand the requirements: The task is to create a TOML (Tom\'s Obvious, Minimal Language) document for a financial report. TOML is a simple, human-readable configuration format often used for storing configuration files or structured data.  \n2. Structure the financial report with logical sections: A typical financial report includes key sections such as metadata (e.g., report title, date, version), financial data (e.g., revenue, expenses, profit), and additional details (e.g., currency, period).  \n3. Use valid TOML syntax: Ensure proper use of keys, values, tables, and nested structures. Avoid invalid syntax like missing commas or incorrect indentation.  \n4. Choose realistic data: Use plausible financial values to represent a sample report.  \n5. Ensure clarity and readability: Organize the data in a way that is easy to parse and understand, both for humans and automated tools.\n\nOutput:  \n```toml\n[report]\ntitle = "Q3 2023 Financial Report"\ndate = "2023-09-30"\nversion = "1.0"\ncurrency = "USD"\n\n[financials]\nrevenue = 1500000\ncost_of_goods_sold = 750000\noperating_expenses = 300000\nnet_profit = 450000\n\n[summary]\ntotal_revenue = 1500000\ntotal_expenses = 1050000\nnet_income = 450000\n\n[metadata]\nsource = "Internal Accounting System"\nperiod = "Q3 2023"\nprepared_by = "Finance Department"\n```', 'strategy': 'model_generated'}

Train size: 225, Eval size: 25

## モデルのロードおよび学習

In [ ]:
from unsloth import FastLanguageModel, PatchDPOTrainer
import torch
from peft import set_peft_model_state_dict
from huggingface_hub import hf_hub_download
from safetensors.torch import load_file
from trl import DPOConfig, DPOTrainer

# --- 1. 事前パッチ ---
PatchDPOTrainer()

# --- 2. モデルロード ---
base_model_id = "Qwen/Qwen3-4B-Instruct-2507"
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = base_model_id,
    max_seq_length = 2048,
    load_in_4bit = True,
    trust_remote_code = True,
)

# --- 3. LoRA層の追加 (r=16に固定) ---
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
)

# --- 4. 0.77の重みを注入 (外科手術) ---
print("🔄 0.77の重みを注入中...")
adapter_weights = hf_hub_download(repo_id="satoyutaka/LLM2025_main_0_DPO3", filename="adapter_model.safetensors")
state_dict = load_file(adapter_weights)
set_peft_model_state_dict(model, state_dict)

# --- 5. DPO学習の設定 (極限まで負荷を下げる) ---
# --- 5. DPO学習の設定 ---
dpo_trainer = DPOTrainer(
    model = model,
    ref_model = None,
    args = DPOConfig(
        per_device_train_batch_size = 1,
        gradient_accumulation_steps = 16, # 8から16に増やして、より安定させてみたよ！
        warmup_ratio = 0.1,
        num_train_epochs = 3,            # 3周でしっかり教育！
        learning_rate = 1e-6,            # 0.77の知能を守るために少し優しく
        fp16 = True,
        bf16 = False,
        logging_steps = 1,
        optim = "adamw_8bit",
        output_dir = "outputs_silent_08", # フォルダ名でやる気アップ！
        beta = 0.1,                      # 「お喋り厳禁！」のスパルタ設定✨
        report_to = "none",
        remove_unused_columns = False,
        max_steps = -1,                  # epoch数で管理
    ),
    train_dataset = train_dataset,
    eval_dataset = eval_dataset,
    tokenizer = tokenizer,
    max_length = 1024,
    max_prompt_length = 512,
)


print("🚀 さあ、学習開始！DPO5")
dpo_trainer.train()

Unsloth: WARNING `trust_remote_code` is True.
Are you certain you want to do remote code execution?
==((====))==  Unsloth 2026.1.4: Fast Qwen3 patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
🔄 0.766の重みを注入中...

adapter_model.safetensors:   0%|          | 0.00/132M [00:00<?, ?B/s]

Extracting prompt in train dataset (num_proc=4):   0%|          | 0/225 [00:00<?, ? examples/s]

Applying chat template to train dataset (num_proc=4):   0%|          | 0/225 [00:00<?, ? examples/s]

Tokenizing train dataset (num_proc=4):   0%|          | 0/225 [00:00<?, ? examples/s]

Extracting prompt in eval dataset (num_proc=4):   0%|          | 0/25 [00:00<?, ? examples/s]

Applying chat template to eval dataset (num_proc=4):   0%|          | 0/25 [00:00<?, ? examples/s]

Tokenizing eval dataset (num_proc=4):   0%|          | 0/25 [00:00<?, ? examples/s]

🚀 さあ、学習開始！DPO5

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 225 | Num Epochs = 3 | Total steps = 45
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 16
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 16 x 1) = 16
 "-____-"     Trainable parameters = 33,030,144 of 4,055,498,240 (0.81% trained)

Unsloth: Will smartly offload gradients to save VRAM!

TrainOutput(global_step=45, training_loss=0.0010311688348439122, metrics={'train_runtime': 1801.555, 'train_samples_per_second': 0.375, 'train_steps_per_second': 0.025, 'total_flos': 0.0, 'train_loss': 0.0010311688348439122, 'epoch': 3.0})

## モデルの保存

In [ ]:
import os

# 1. 保存パスの設定（struct-eval-comp プロジェクト用）
adapter_name = "struct-eval-comp-dpo-v5"
drive_save_path = f"/content/drive/MyDrive/LLM2026/main_competition/DPO/{adapter_name}"
hf_model_id = "satoyutaka/LLM2025_main_0_DPO4" # 自分のHFユーザー名に合わせてね

# 2. Google ドライブへ保存
print(f"💾 Googleドライブに保存中: {drive_save_path}")
os.makedirs(drive_save_path, exist_ok=True)
model.save_pretrained(drive_save_path)
tokenizer.save_pretrained(drive_save_path)

# 3. Hugging Face へアップロード
print(f"🚀 Hugging Faceにアップロード中: {hf_model_id}")
try:
    model.push_to_hub(hf_model_id)
    tokenizer.push_to_hub(hf_model_id)
    print("✅ HFへのアップロードも完了したよ！")
except Exception as e:
    print(f"⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: {e}")

print("\n✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！")

💾 Googleドライブに保存中: /content/drive/MyDrive/LLM2026/main_competition/DPO/struct-eval-comp-dpo-v5
🚀 Hugging Faceにアップロード中: satoyutaka/LLM2025_main_0_DPO4
⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: (Request ID: Root=1-69867bc2-0d9f13840cf1c7e66f486a15;9c8ef2e0-db97-43a7-9acf-fc56d8224854)

403 Forbidden: You don't have the rights to create a model under the namespace "satoyutaka".
Cannot access content at: https://huggingface.co/api/repos/create.
Make sure your token has the correct permissions.

✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！

# 6回目

【学習実行：知能維持型・高精度フォーマット矯正学習】

■ 戦略概要 現在の最高スコア個体である「0.77064モデル（DPO Ver.3）」をベースモデルとして採用し、外科手術的な重み注入（Weight Injection）を行った上で、最終的な微調整（Fine-Tuning）を実施する。

■ ハイパーパラメータの設定意図

Learning Rate (1e-6): 既存の高度な知識を破壊しないよう、極めて低学習率で「お作法（出力形式）」の調整に特化させる。

Beta (0.1): 形式的な誤り（Markdownの残存等）に対して、標準設定以上のペナルティを課すことで、より厳格な出力制御を実現する。

Epochs (1~2): 過学習による「知能の退行（バカ化）」を防ぐため、反復回数を最小限に留め、データ整形による「癖の修正」のみを目的とする。

■ 期待される成果 高い推論能力（0.77相当）を保持したまま、推論結果からMarkdownブロックを完全に排除することで、コンペティション採点システムにおける完全一致スコアの最大化、および0.80の大台突破を狙う。

## データのロード

In [ ]:
from datasets import load_dataset

# 1. 保存したjsonlファイルを読み込む
# 先ほどのスクリプトと同じディレクトリにあることを想定しているよ
data_files = {
    "train": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/struct_special_6_dpo_train.jsonl",
    "eval": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/struct_special_6_dpo_eval.jsonl"
}

# json形式でロード
dataset = load_dataset("json", data_files=data_files)

# 2. train と eval に切り分け
train_dataset = dataset["train"]
eval_dataset = dataset["eval"]

# 3. 中身の確認（デバッグ用：最初の1件を表示）
print("--- Train Dataset Sample ---")
print(train_dataset[0])
print(f"\nTrain size: {len(train_dataset)}, Eval size: {len(eval_dataset)}")

--- Train Dataset Sample ---
{'prompt': '### Instruction:\n<|im_start|>system\nYou are a helpful assistant. Please format your response as follows:\nApproach: <step-by-step reasoning>\nOutput: <final answer><|im_end|>\n<|im_start|>user\nOutput prescription as XML.<|im_end|>\n<|im_start|>assistant\n\n\n### Response:\n', 'chosen': 'Approach:\n1. Task: Create prescription in XML\n2. Complexity: medium - 5-8 fields, 2-3 levels\n3. Format rules: well-formed tags, proper nesting, escaped special chars\n4. Structure: Organize data logically with appropriate nesting\n5. Populate fields with realistic example data based on the schema.\n\nOutput:\n<?xml version="1.0" encoding="UTF-8"?>\n<prescription>\n<rx_id>RX-4085457</rx_id>\n<patient_mrn>MRN-357420</patient_mrn>\n<prescriber>Paul Contreras</prescriber>\n<date>2026-01-01</date>\n<medications>\n<name>Lisinopril</name>\n<dosage>10mg</dosage>\n<frequency>BID</frequency>\n<quantity>30</quantity>\n</medications>\n<medications>\n<name>Metformin</name>\n<dosage>10mg</dosage>\n<frequency>daily</frequency>\n<quantity>90</quantity>\n</medications>\n</prescription>', 'rejected': 'Approach:  \n1. Understand that the user request is to "output prescription as XML," which implies generating a structured XML document representing a prescription.  \n2. Since no specific prescription details (e.g., patient name, medication, dosage, instructions) were provided, I will create a generic, valid XML prescription template with common fields.  \n3. Structure the XML with standard elements such as prescription header (patient, provider, date), medication details (name, dosage, quantity, instructions), and signature or status.  \n4. Ensure the XML follows valid syntax with proper nesting, closing tags, and correct use of attributes.  \n5. Present the output in a clean, readable format as requested.  \n\nOutput:  \n<prescription>  \n  <header>  \n    <patientName>John Doe</patientName>  \n    <patientId>123456</patientId>  \n    <providerName>Dr. Jane Smith</providerName>  \n    <providerId>PRV7890</providerId>  \n    <prescriptionDate>2023-10-05</prescriptionDate>  \n    <prescriptionNumber>P12345</prescriptionNumber>  \n  </header>  \n  <medications>  \n    <medication>  \n      <name>Atorvastatin</name>  \n      <form>Tablet</form>  \n      <dosage>20 mg</dosage>  \n      <route>Oral</route>  \n      <frequency>Once daily</frequency>  \n      <duration>30 days</duration>  \n      <instructions>Take with food</instructions>  \n      <quantity>30</quantity>  \n    </medication>  \n    <medication>  \n      <name>Lisinopril</name>  \n      <form>Tablet</form>  \n      <dosage>10 mg</dosage>  \n      <route>Oral</route>  \n      <frequency>Once daily</frequency>  \n      <duration>30 days</duration>  \n      <instructions>Take in the morning</instructions>  \n      <quantity>30</quantity>  \n    </medication>  \n  </medications>  \n  <status>Active</status>  \n  <signature>Dr. Jane Smith</signature>  \n</prescription>', 'strategy': 'model_generated'}

Train size: 225, Eval size: 25

## モデルのロードおよび学習

In [ ]:
# 1. ライブラリを最新に更新して、衝突を解消するよ！
!pip install --upgrade huggingface_hub unsloth

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (0.36.2)
Collecting huggingface_hub
  Using cached huggingface_hub-1.4.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: unsloth in /usr/local/lib/python3.12/dist-packages (2026.1.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.20.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.5.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.21.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: unsloth_zoo>=2026.1.4 in /usr/local/lib/python3.12/dist-packages (from unsloth) (2026.1.4)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.46.3)
Requirement already satisfied: torch>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.9.0+cu126)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.24.0+cu126)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.9.5)
Requirement already satisfied: tyro in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.0.6)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.29.5)
Requirement already satisfied: xformers>=0.0.27.post2 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.0.33.post1)
Requirement already satisfied: bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.49.1)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (3.5.0)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.2.1)
Requirement already satisfied: datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.3.0)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.4.0)
Requirement already satisfied: peft!=0.11.0,>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.18.1)
Requirement already satisfied: hf_transfer in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.1.9)
Requirement already satisfied: diffusers in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.36.0)
Requirement already satisfied: transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,<=4.57.6,>=4.51.3 in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.56.2)
Requirement already satisfied: trl!=0.19.0,<=0.24.0,>=0.18.2 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.34.1->unsloth) (0.7.0)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (23.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.70.16)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.11.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,<=4.57.6,>=4.51.3->unsloth) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,<=4.57.6,>=4.51.3->unsloth) (0.22.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.5.0)
Requirement already satisfied: torchao>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (0.15.0)
Requirement already satisfied: cut_cross_entropy in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (25.1.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (11.3.0)
Requirement already satisfied: msgspec in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (0.20.0)
Requirement already satisfied: importlib_metadata in /usr/local/lib/python3.12/dist-packages (from diffusers->unsloth) (8.7.1)
Requirement already satisfied: docstring-parser>=0.15 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (0.17.0)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (4.4.4)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.13.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.4.0->unsloth) (1.3.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata->diffusers->unsloth) (3.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.4.0->unsloth) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.17.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface_hub) (8.3.1)

In [ ]:
from unsloth import FastLanguageModel, PatchDPOTrainer
import torch
from peft import set_peft_model_state_dict
from huggingface_hub import hf_hub_download
from safetensors.torch import load_file
from trl import DPOConfig, DPOTrainer

# --- 1. 事前パッチ ---
PatchDPOTrainer()

# --- 2. モデルロード ---
base_model_id = "Qwen/Qwen3-4B-Instruct-2507"
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = base_model_id,
    max_seq_length = 2048,
    load_in_4bit = True,
    trust_remote_code = True,
)

# --- 3. LoRA層の追加 (r=16に固定) ---
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
)

# --- 4. 0.77の重みを注入 (外科手術) ---
print("🔄 0.77の重みを注入中...")
adapter_weights = hf_hub_download(repo_id="satoyutaka/LLM2025_main_0_DPO3", filename="adapter_model.safetensors")
state_dict = load_file(adapter_weights)
set_peft_model_state_dict(model, state_dict)

# --- 5. DPO学習の設定 (極限まで負荷を下げる) ---
# --- 5. DPO学習の設定 ---
dpo_trainer = DPOTrainer(
    model = model,
    ref_model = None,
    args = DPOConfig(
        per_device_train_batch_size = 1,
        gradient_accumulation_steps = 16, # 8から16に増やして、より安定させてみたよ！
        warmup_ratio = 0.1,
        num_train_epochs = 1,            # 3周でしっかり教育！
        learning_rate = 1e-6,            # 0.77の知能を守るために少し優しく
        fp16 = True,
        bf16 = False,
        logging_steps = 1,
        optim = "adamw_8bit",
        output_dir = "outputs_silent_08", # フォルダ名でやる気アップ！
        beta = 0.1,                      # 「お喋り厳禁！」のスパルタ設定✨
        report_to = "none",
        remove_unused_columns = False,
        max_steps = -1,                  # epoch数で管理
    ),
    train_dataset = train_dataset,
    eval_dataset = eval_dataset,
    tokenizer = tokenizer,
    max_length = 1024,
    max_prompt_length = 512,
)


print("🚀 さあ、学習開始！DPO6")
dpo_trainer.train()

Unsloth: WARNING `trust_remote_code` is True.
Are you certain you want to do remote code execution?
==((====))==  Unsloth 2026.1.4: Fast Qwen3 patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
🔄 0.77の重みを注入中...

Extracting prompt in train dataset (num_proc=4):   0%|          | 0/225 [00:00<?, ? examples/s]

Applying chat template to train dataset (num_proc=4):   0%|          | 0/225 [00:00<?, ? examples/s]

Tokenizing train dataset (num_proc=4):   0%|          | 0/225 [00:00<?, ? examples/s]

Extracting prompt in eval dataset (num_proc=4):   0%|          | 0/25 [00:00<?, ? examples/s]

Applying chat template to eval dataset (num_proc=4):   0%|          | 0/25 [00:00<?, ? examples/s]

Tokenizing eval dataset (num_proc=4):   0%|          | 0/25 [00:00<?, ? examples/s]

🚀 さあ、学習開始！DPO6

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 225 | Num Epochs = 1 | Total steps = 15
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 16
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 16 x 1) = 16
 "-____-"     Trainable parameters = 33,030,144 of 4,055,498,240 (0.81% trained)

Unsloth: Will smartly offload gradients to save VRAM!

TrainOutput(global_step=15, training_loss=0.002907154139461454, metrics={'train_runtime': 578.9142, 'train_samples_per_second': 0.389, 'train_steps_per_second': 0.026, 'total_flos': 0.0, 'train_loss': 0.002907154139461454, 'epoch': 1.0})

## モデルの保存

In [ ]:
import os

# 1. 保存パスの設定（struct-eval-comp プロジェクト用）
adapter_name = "struct-eval-comp-dpo-v6"
drive_save_path = f"/content/drive/MyDrive/LLM2026/main_competition/DPO/{adapter_name}"
hf_model_id = "satoyutaka/LLM2025_main_0_DPO6" # 自分のHFユーザー名に合わせてね

# 2. Google ドライブへ保存
print(f"💾 Googleドライブに保存中: {drive_save_path}")
os.makedirs(drive_save_path, exist_ok=True)
model.save_pretrained(drive_save_path)
tokenizer.save_pretrained(drive_save_path)

# 3. Hugging Face へアップロード
print(f"🚀 Hugging Faceにアップロード中: {hf_model_id}")
try:
    model.push_to_hub(hf_model_id)
    tokenizer.push_to_hub(hf_model_id)
    print("✅ HFへのアップロードも完了したよ！")
except Exception as e:
    print(f"⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: {e}")

print("\n✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！")

💾 Googleドライブに保存中: /content/drive/MyDrive/LLM2026/main_competition/DPO/struct-eval-comp-dpo-v6
🚀 Hugging Faceにアップロード中: satoyutaka/LLM2025_main_0_DPO6
⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: (Request ID: Root=1-6986e74a-4e3d52e372dda76d2dfc2862;e11d70c2-800f-47b4-b481-088a36a83c6b)

403 Forbidden: You don't have the rights to create a model under the namespace "satoyutaka".
Cannot access content at: https://huggingface.co/api/repos/create.
Make sure your token has the correct permissions.

✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！

# ７回目

In [ ]:
# 1. ライブラリを最新に更新して、衝突を解消するよ！
!pip install --upgrade huggingface_hub unsloth

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (0.36.2)
Collecting huggingface_hub
  Using cached huggingface_hub-1.4.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: unsloth in /usr/local/lib/python3.12/dist-packages (2025.12.7)
Collecting unsloth
  Using cached unsloth-2026.1.4-py3-none-any.whl.metadata (66 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.20.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.5.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.21.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Collecting unsloth_zoo>=2026.1.4 (from unsloth)
  Using cached unsloth_zoo-2026.1.4-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.46.3)
Requirement already satisfied: torch>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.9.0+cu126)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.24.0+cu126)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.9.5)
Requirement already satisfied: tyro in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.0.6)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.29.5)
Requirement already satisfied: xformers>=0.0.27.post2 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.0.33.post1)
Requirement already satisfied: bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.49.1)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (3.5.0)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.2.1)
Requirement already satisfied: datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.3.0)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.4.0)
Collecting peft!=0.11.0,>=0.18.0 (from unsloth)
  Using cached peft-0.18.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: hf_transfer in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.1.9)
Requirement already satisfied: diffusers in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.36.0)
Requirement already satisfied: transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,<=4.57.6,>=4.51.3 in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.56.2)
Requirement already satisfied: trl!=0.19.0,<=0.24.0,>=0.18.2 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.34.1->unsloth) (0.7.0)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (23.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.70.16)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.11.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,<=4.57.6,>=4.51.3->unsloth) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,<=4.57.6,>=4.51.3->unsloth) (0.22.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.5.0)
Requirement already satisfied: torchao>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (0.15.0)
Requirement already satisfied: cut_cross_entropy in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (25.1.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (11.3.0)
Requirement already satisfied: msgspec in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (0.20.0)
Requirement already satisfied: importlib_metadata in /usr/local/lib/python3.12/dist-packages (from diffusers->unsloth) (8.7.1)
Requirement already satisfied: docstring-parser>=0.15 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (0.17.0)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (4.4.4)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.13.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.4.0->unsloth) (1.3.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata->diffusers->unsloth) (3.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.4.0->unsloth) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.17.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface_hub) (8.3.1)
Using cached unsloth-2026.1.4-py3-none-any.whl (405 kB)
Using cached peft-0.18.1-py3-none-any.whl (556 kB)
Using cached unsloth_zoo-2026.1.4-py3-none-any.whl (310 kB)
Installing collected packages: peft, unsloth_zoo, unsloth
  Attempting uninstall: peft
    Found existing installation: peft 0.13.2
    Uninstalling peft-0.13.2:
      Successfully uninstalled peft-0.13.2
  Attempting uninstall: unsloth_zoo
    Found existing installation: unsloth_zoo 2025.12.7
    Uninstalling unsloth_zoo-2025.12.7:
      Successfully uninstalled unsloth_zoo-2025.12.7
  Attempting uninstall: unsloth
    Found existing installation: unsloth 2025.12.7
    Uninstalling unsloth-2025.12.7:
      Successfully uninstalled unsloth-2025.12.7
Successfully installed peft-0.18.1 unsloth-2026.1.4 unsloth_zoo-2026.1.4

🛠️ 学習プロセスと設定の解説（真面目版）
このセルでは、前回の最高スコア（0.77136）を記録したモデルをベースに、さらに精度を高めるための継続的DPO学習を実行しています。 「推論の正確さ」と「形式の美しさ」を両立させるために、以下の高度な手法を取り入れています。

1. 既存アダプターの「重み注入」（Weight Injection）

新しいLoRA層を作成した後、前回スコアの良かったアダプター重み（LLM2025_main_0_DPO3）をプログラム的に注入しています。これにより、ゼロから学習し直すのではなく、**「すでに0.77の知能を持った状態」**から学習をスタートでき、効率的にスコアを伸ばすことが可能です。

2. DPOハイパーパラメータの最適化

Beta = 0.1: Beta値は、モデルが「元のベースモデルからどれだけ離れて良いか」を制御します。0.1に設定することで、モデルが自分の本来の推論能力（ベースモデルの賢さ）を捨てすぎることなく、フォーマットの矯正に集中できるようバランスを取っています。

Learning Rate = 8e-7: 通常のSFTよりも極めて低い学習率を採用しています。これは、既存の高度な推論知識を「破壊」せず、Markdown装飾の排除といった「出力スタイルの微調整」のみを精密に行うための設定です。

3. 多重エポックによる徹底教育

前回の実験では、1エポック（学習データ1周）ではQwen特有の「Markdownコードブロックで回答を囲む」というバイアスを完全に抜けきることができませんでした。今回は3エポックの学習を行うことで、作成した高品質なデータセットのパターンを深く定着させ、装飾の完全排除を目指します。

4. 勾配累積（Gradient Accumulation）の活用

GPUメモリの制約上、一度に処理できるバッチサイズは「1」に制限されていますが、gradient_accumulation_steps = 16 を設定することで、内部的には16サンプル分の情報をまとめてから重みを更新しています。これにより、少ない計算資源でも、大規模なマシンで学習させた時のような安定した学習進捗を実現しています。

## データのロード

In [ ]:
from datasets import load_dataset

# 1. 保存したjsonlファイルを読み込む
# 先ほどのスクリプトと同じディレクトリにあることを想定しているよ
data_files = {
    "train": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/struct_special_7_dpo_train.jsonl",
    "eval": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/struct_special_7_dpo_eval.jsonl"
}

# json形式でロード
dataset = load_dataset("json", data_files=data_files)

# 2. train と eval に切り分け
train_dataset = dataset["train"]
eval_dataset = dataset["eval"]

# 3. 中身の確認（デバッグ用：最初の1件を表示）
print("--- Train Dataset Sample ---")
print(train_dataset[0])
print(f"\nTrain size: {len(train_dataset)}, Eval size: {len(eval_dataset)}")

--- Train Dataset Sample ---
{'prompt': '### Instruction:\n<|im_start|>system\nYou are a helpful assistant. Please format your response as follows:\nApproach: <step-by-step reasoning>\nOutput: <final answer><|im_end|>\n<|im_start|>user\nOutput api specification as XML.<|im_end|>\n<|im_start|>assistant\n\n\n### Response:\n', 'chosen': 'Approach:\n1. Task: Create api specification in XML\n2. Complexity: medium - 5-8 fields, 2-3 levels\n3. Format rules: well-formed tags, proper nesting, escaped special chars\n4. Structure: Organize data logically with appropriate nesting\n5. Populate fields with realistic example data based on the schema.\n\nOutput:\n<?xml version="1.0" encoding="UTF-8"?>\n<api_specification>\n<openapi>3.0.0</openapi>\n<info>\n<title>Multi-lateral demand-driven matrices API</title>\n<version>1.0.0</version>\n</info>\n<paths>\n</speech>\n<get>\n<summary>According institution everybody bad listen nearly.</summary>\n<parameters>\n<name>param0</name>\n<in>query</in>\n<type>string</type>\n</parameters>\n<parameters>\n<name>param1</name>\n<in>query</in>\n<type>string</type>\n</parameters>\n<responses>\n<200>\n<description>Success</description>\n</200>\n<400>\n<description>Bad Request</description>\n</400>\n</responses>\n</get>\n<//speech>\n</paths>\n</api_specification>', 'rejected': 'Approach:  \n1. Understand the request: The user is asking to "output API specification as XML." This means they want a well-structured, machine-readable XML format that defines an API, typically including endpoints, methods, parameters, request/response formats, and other relevant details.  \n2. Create a generic but comprehensive API specification in XML format. This includes common elements like API version, base URL, endpoints, methods (GET, POST, etc.), parameters, and examples.  \n3. Ensure the XML is valid, properly nested, and follows standard conventions for API documentation (e.g., similar to OpenAPI/Swagger in XML form).  \n4. Avoid assumptions about specific services or technologies unless necessary—keep it general enough to be reusable.  \n\nOutput:  \n<apiSpecification>  \n  <api>  \n    <name>Sample REST API</name>  \n    <version>1.0</version>  \n    <baseURL>https://api.example.com/v1</baseURL>  \n    <description>Sample API for demonstrating data retrieval and submission.</description>  \n    <contact>  \n      <email>support@example.com</email>  \n      <website>https://example.com</website>  \n    </contact>  \n    <endpoints>  \n      <endpoint>  \n        <path>/users</path>  \n        <method>GET</method>  \n        <description>Retrieve a list of all users.</description>  \n        <parameters>  \n          <parameter>  \n            <name>page</name>  \n            <type>integer</type>  \n            <required>false</required>  \n            <description>Page number (default: 1).</description>  \n          </parameter>  \n          <parameter>  \n            <name>limit</name>  \n            <type>integer</type>  \n            <required>false</required>  \n            <description>Number of items per page (default: 10).</description>  \n          </parameter>  \n        </parameters>  \n        <response>  \n          <status>200</status>  \n          <contentType>application/json</contentType>  \n          <example>  \n            [{"id":1,"name":"Alice"},{"id":2,"name":"Bob"}]  \n          </example>  \n        </response>  \n      </endpoint>  \n      <endpoint>  \n        <path>/users/{id}</path>  \n        <method>GET</method>  \n        <description>Retrieve a specific user by ID.</description>  \n        <parameters>  \n          <parameter>  \n            <name>id</name>  \n            <type>integer</type>  \n            <required>true</required>  \n            <description>User ID.</description>  \n          </parameter>  \n        </parameters>  \n        <response>  \n          <status>200</status>  \n          <contentType>application/json</contentType>  \n          <example>  \n            {"id":1,"name":"Alice","email":"alice@example.com"}  \n          </example>  \n        </response>  \n      </endpoint>  \n      <endpoint>  \n        <path>/users</path>  \n        <method>POST</method>  \n        <description>Create a new user.</description>  \n        <request>  \n          <contentType>application/json</contentType>  \n          <example>  \n            {  \n              "name": "Charlie",  \n              "email": "charlie@example.com"  \n            }  \n          </example>  \n        </request>  \n        <response>  \n          <status>201</status>  \n          <contentType>application/json</contentType>  \n          <example>  \n            {"id":3,"name":"Charlie","email":"charlie@example.com"}  \n          </example>  \n        </response>  \n      </endpoint>  \n    </endpoints>  \n  </api>  \n</apiSpecification>', 'strategy': 'model_generated', 'logic_score': 12.187825202941895}

Train size: 225, Eval size: 25

## モデルのロードおよび学習

In [ ]:
from unsloth import FastLanguageModel, PatchDPOTrainer
import torch
from peft import set_peft_model_state_dict
from huggingface_hub import hf_hub_download
from safetensors.torch import load_file
from trl import DPOConfig, DPOTrainer

# --- 1. 事前パッチ ---
PatchDPOTrainer()

# --- 2. モデルロード ---
base_model_id = "Qwen/Qwen3-4B-Instruct-2507"
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = base_model_id,
    max_seq_length = 2048,
    load_in_4bit = True,
    trust_remote_code = True,
)

# --- 3. LoRA層の追加 ---
# Rank(r)を維持しつつ、学習効率を最大化するよ。
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
)

# --- 4. 0.77の重みを注入 (外科手術) ---
# 前回の最高傑作(DPO3/v6)の重みをロードして、ここをスタート地点にするよ！
print("🔄 前回の最高傑作（0.77）の知能を注入中...")
adapter_weights = hf_hub_download(repo_id="satoyutaka/LLM2025_main_0_DPO6", filename="adapter_model.safetensors")
state_dict = load_file(adapter_weights)
set_peft_model_state_dict(model, state_dict)

# --- 5. DPO学習の設定（0.80突破用スパルタ設定） ---
dpo_trainer = DPOTrainer(
    model = model,
    ref_model = None, # UnslothならNoneでメモリ節約！
    args = DPOConfig(
        per_device_train_batch_size = 1,
        gradient_accumulation_steps = 16, # バッチサイズを仮想的に増やして学習を安定させる
        warmup_ratio = 0.1,
        num_train_epochs = 3,            # 1周では抜けなかった癖を3周で徹底排除！
        learning_rate = 8e-7,            # 1e-6より少し慎重に、既存の知能を壊さない速度
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        output_dir = "outputs_struct_eval_v7",
        beta = 0.1,                      # 推論能力を守るための適度な重み（KLダイバージェンス）
        report_to = "none",
        remove_unused_columns = False,
    ),
    train_dataset = train_dataset, # さっきBERTで作った精鋭データ
    eval_dataset = eval_dataset,   # 検証用データ
    tokenizer = tokenizer,
    max_length = 1024,
    max_prompt_length = 512,
)

print("🚀 0.80の壁を壊しにいこう！学習開始！")
dpo_trainer.train()

Unsloth: WARNING `trust_remote_code` is True.
Are you certain you want to do remote code execution?
==((====))==  Unsloth 2026.1.4: Fast Qwen3 patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
🔄 前回の最高傑作（0.77）の知能を注入中...
🚀 0.80の壁を壊しにいこう！学習開始！

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 225 | Num Epochs = 3 | Total steps = 45
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 16
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 16 x 1) = 16
 "-____-"     Trainable parameters = 33,030,144 of 4,055,498,240 (0.81% trained)

Unsloth: Will smartly offload gradients to save VRAM!

TrainOutput(global_step=45, training_loss=0.006161588863728361, metrics={'train_runtime': 2083.1808, 'train_samples_per_second': 0.324, 'train_steps_per_second': 0.022, 'total_flos': 0.0, 'train_loss': 0.006161588863728361, 'epoch': 3.0})

## モデルの保存

In [ ]:
import os

# 1. 保存パスの設定（struct-eval-comp プロジェクト用）
adapter_name = "struct-eval-comp-dpo-v7"
drive_save_path = f"/content/drive/MyDrive/LLM2026/main_competition/DPO/{adapter_name}"
hf_model_id = "satoyutaka/LLM2025_main_0_DPO6" # 自分のHFユーザー名に合わせてね

# 2. Google ドライブへ保存
print(f"💾 Googleドライブに保存中: {drive_save_path}")
os.makedirs(drive_save_path, exist_ok=True)
model.save_pretrained(drive_save_path)
tokenizer.save_pretrained(drive_save_path)

# 3. Hugging Face へアップロード
print(f"🚀 Hugging Faceにアップロード中: {hf_model_id}")
try:
    model.push_to_hub(hf_model_id)
    tokenizer.push_to_hub(hf_model_id)
    print("✅ HFへのアップロードも完了したよ！")
except Exception as e:
    print(f"⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: {e}")

print("\n✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！")

💾 Googleドライブに保存中: /content/drive/MyDrive/LLM2026/main_competition/DPO/struct-eval-comp-dpo-v7
🚀 Hugging Faceにアップロード中: satoyutaka/LLM2025_main_0_DPO6
⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: (Request ID: Root=1-698728ed-0cad97e923b360f40bbca3ba;99b16a72-6080-4924-ba5f-8c66558d0c77)

403 Forbidden: Forbidden: you must use a write token to upload to a repository..
Cannot access content at: https://huggingface.co/api/models/satoyutaka/LLM2025_main_0_DPO6/preupload/main.
Make sure your token has the correct permissions.

✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！

# 8回目

In [ ]:
# 1. ライブラリを最新に更新して、衝突を解消するよ！
!pip install --upgrade huggingface_hub unsloth

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (0.36.2)
Collecting huggingface_hub
  Using cached huggingface_hub-1.4.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: unsloth in /usr/local/lib/python3.12/dist-packages (2026.1.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.20.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.5.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.21.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: unsloth_zoo>=2026.1.4 in /usr/local/lib/python3.12/dist-packages (from unsloth) (2026.1.4)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.46.3)
Requirement already satisfied: torch>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.9.0+cu126)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.24.0+cu126)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.9.5)
Requirement already satisfied: tyro in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.0.6)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.29.5)
Requirement already satisfied: xformers>=0.0.27.post2 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.0.33.post1)
Requirement already satisfied: bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.49.1)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (3.5.0)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.2.1)
Requirement already satisfied: datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.3.0)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.4.0)
Requirement already satisfied: peft!=0.11.0,>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.18.1)
Requirement already satisfied: hf_transfer in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.1.9)
Requirement already satisfied: diffusers in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.36.0)
Requirement already satisfied: transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,<=4.57.6,>=4.51.3 in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.56.2)
Requirement already satisfied: trl!=0.19.0,<=0.24.0,>=0.18.2 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.34.1->unsloth) (0.7.0)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (23.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.70.16)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.11.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,<=4.57.6,>=4.51.3->unsloth) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,<=4.57.6,>=4.51.3->unsloth) (0.22.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.5.0)
Requirement already satisfied: torchao>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (0.15.0)
Requirement already satisfied: cut_cross_entropy in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (25.1.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (11.3.0)
Requirement already satisfied: msgspec in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (0.20.0)
Requirement already satisfied: importlib_metadata in /usr/local/lib/python3.12/dist-packages (from diffusers->unsloth) (8.7.1)
Requirement already satisfied: docstring-parser>=0.15 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (0.17.0)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (4.4.4)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.13.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.4.0->unsloth) (1.3.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata->diffusers->unsloth) (3.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.4.0->unsloth) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.17.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface_hub) (8.3.1)

🚀 DPO学習：V8 スタイル矯正・最終フェーズ（スパルタ設定）
このセルでは、前回の DPO V7 で到達した最高スコア（0.77136）をベースに、出力フォーマットの完全性を追求するための**追加の微調整（Fine-tuning）**を実行します。

1. V8 の戦略的背景

V7 の分析により、モデルは「思考プロセス（Approach）」と「正しい抽出能力」を高いレベルで両立させていることが確認されました。しかし、ベースモデル（Qwen）が持つ「回答を Markdown コードブロックで囲む」という強力な先天的バイアスが、依然として数点のスコアロスを招いています。 V8 では、データの質はそのままに、**学習の「厳格さ」**を一段階引き上げることで、このバイアスを打破します。

2. ハイパーパラメータの攻撃的最適化

Beta = 0.01（極限設定）: Beta 値を V7（0.1）の 10 分の 1 まで下げています。これにより、モデルが「ベースモデルの元の傾向（Markdown 囲い）」に従おうとする制約を弱め、「Markdown なしの生データ出力」という今回の選好データに 100% 同期するように仕向けます。

Learning Rate = 2e-6: すでに学習済みの概念を定着させるため、V7 よりわずかに高い学習率を設定し、短期間（1 エポック）でスタイル変更を強力に焼き付けます。

3. 継続学習（Continued Training）のメリット

V7 の重みをスタート地点とすることで、ゼロから学習するリスクを避けつつ、**「知能は 0.77 以上のまま、見た目だけを矯正する」**という、コンペティションにおいて最も効率的な最適化を狙っています。

4. 期待される効果

この学習を完走させることで、推論結果からパースエラー（不必要な ```json 等）を完全に排除し、0.80 の壁を突破するクリーンな構造化データ出力を実現します。

## データのロード

In [ ]:
from datasets import load_dataset

# 1. 保存したjsonlファイルを読み込む
# 先ほどのスクリプトと同じディレクトリにあることを想定しているよ
data_files = {
    "train": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/struct_special_7_dpo_train.jsonl",
    "eval": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/struct_special_7_dpo_eval.jsonl"
}

# json形式でロード
dataset = load_dataset("json", data_files=data_files)

# 2. train と eval に切り分け
train_dataset = dataset["train"]
eval_dataset = dataset["eval"]

# 3. 中身の確認（デバッグ用：最初の1件を表示）
print("--- Train Dataset Sample ---")
print(train_dataset[0])
print(f"\nTrain size: {len(train_dataset)}, Eval size: {len(eval_dataset)}")

--- Train Dataset Sample ---
{'prompt': '### Instruction:\n<|im_start|>system\nYou are a helpful assistant. Please format your response as follows:\nApproach: <step-by-step reasoning>\nOutput: <final answer><|im_end|>\n<|im_start|>user\nOutput api specification as XML.<|im_end|>\n<|im_start|>assistant\n\n\n### Response:\n', 'chosen': 'Approach:\n1. Task: Create api specification in XML\n2. Complexity: medium - 5-8 fields, 2-3 levels\n3. Format rules: well-formed tags, proper nesting, escaped special chars\n4. Structure: Organize data logically with appropriate nesting\n5. Populate fields with realistic example data based on the schema.\n\nOutput:\n<?xml version="1.0" encoding="UTF-8"?>\n<api_specification>\n<openapi>3.0.0</openapi>\n<info>\n<title>Multi-lateral demand-driven matrices API</title>\n<version>1.0.0</version>\n</info>\n<paths>\n</speech>\n<get>\n<summary>According institution everybody bad listen nearly.</summary>\n<parameters>\n<name>param0</name>\n<in>query</in>\n<type>string</type>\n</parameters>\n<parameters>\n<name>param1</name>\n<in>query</in>\n<type>string</type>\n</parameters>\n<responses>\n<200>\n<description>Success</description>\n</200>\n<400>\n<description>Bad Request</description>\n</400>\n</responses>\n</get>\n<//speech>\n</paths>\n</api_specification>', 'rejected': 'Approach:  \n1. Understand the request: The user is asking to "output API specification as XML." This means they want a well-structured, machine-readable XML format that defines an API, typically including endpoints, methods, parameters, request/response formats, and other relevant details.  \n2. Create a generic but comprehensive API specification in XML format. This includes common elements like API version, base URL, endpoints, methods (GET, POST, etc.), parameters, and examples.  \n3. Ensure the XML is valid, properly nested, and follows standard conventions for API documentation (e.g., similar to OpenAPI/Swagger in XML form).  \n4. Avoid assumptions about specific services or technologies unless necessary—keep it general enough to be reusable.  \n\nOutput:  \n<apiSpecification>  \n  <api>  \n    <name>Sample REST API</name>  \n    <version>1.0</version>  \n    <baseURL>https://api.example.com/v1</baseURL>  \n    <description>Sample API for demonstrating data retrieval and submission.</description>  \n    <contact>  \n      <email>support@example.com</email>  \n      <website>https://example.com</website>  \n    </contact>  \n    <endpoints>  \n      <endpoint>  \n        <path>/users</path>  \n        <method>GET</method>  \n        <description>Retrieve a list of all users.</description>  \n        <parameters>  \n          <parameter>  \n            <name>page</name>  \n            <type>integer</type>  \n            <required>false</required>  \n            <description>Page number (default: 1).</description>  \n          </parameter>  \n          <parameter>  \n            <name>limit</name>  \n            <type>integer</type>  \n            <required>false</required>  \n            <description>Number of items per page (default: 10).</description>  \n          </parameter>  \n        </parameters>  \n        <response>  \n          <status>200</status>  \n          <contentType>application/json</contentType>  \n          <example>  \n            [{"id":1,"name":"Alice"},{"id":2,"name":"Bob"}]  \n          </example>  \n        </response>  \n      </endpoint>  \n      <endpoint>  \n        <path>/users/{id}</path>  \n        <method>GET</method>  \n        <description>Retrieve a specific user by ID.</description>  \n        <parameters>  \n          <parameter>  \n            <name>id</name>  \n            <type>integer</type>  \n            <required>true</required>  \n            <description>User ID.</description>  \n          </parameter>  \n        </parameters>  \n        <response>  \n          <status>200</status>  \n          <contentType>application/json</contentType>  \n          <example>  \n            {"id":1,"name":"Alice","email":"alice@example.com"}  \n          </example>  \n        </response>  \n      </endpoint>  \n      <endpoint>  \n        <path>/users</path>  \n        <method>POST</method>  \n        <description>Create a new user.</description>  \n        <request>  \n          <contentType>application/json</contentType>  \n          <example>  \n            {  \n              "name": "Charlie",  \n              "email": "charlie@example.com"  \n            }  \n          </example>  \n        </request>  \n        <response>  \n          <status>201</status>  \n          <contentType>application/json</contentType>  \n          <example>  \n            {"id":3,"name":"Charlie","email":"charlie@example.com"}  \n          </example>  \n        </response>  \n      </endpoint>  \n    </endpoints>  \n  </api>  \n</apiSpecification>', 'strategy': 'model_generated', 'logic_score': 12.187825202941895}

Train size: 225, Eval size: 25

## モデルのロードおよび学習

In [ ]:
from unsloth import FastLanguageModel, PatchDPOTrainer
import torch
from peft import set_peft_model_state_dict
from huggingface_hub import hf_hub_download
from safetensors.torch import load_file
from trl import DPOConfig, DPOTrainer

# --- 1. 事前パッチ ---
PatchDPOTrainer()

# --- 2. モデルロード ---
base_model_id = "Qwen/Qwen3-4B-Instruct-2507"
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = base_model_id,
    max_seq_length = 2048,
    load_in_4bit = True,
    trust_remote_code = True,
)

# --- 3. LoRA層の追加 ---
# Rank(r)を維持しつつ、学習効率を最大化するよ。
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
)

# --- 4. 0.77の重みを注入 (外科手術) ---
# 前回の最高傑作(DPO3/v6)の重みをロードして、ここをスタート地点にするよ！
print("🔄 前回の最高傑作（0.77）の知能を注入中...")
adapter_weights = hf_hub_download(repo_id="satoyutaka/LLM2025_main_0_DPO7", filename="adapter_model.safetensors")
state_dict = load_file(adapter_weights)
set_peft_model_state_dict(model, state_dict)

## --- V8: スパルタ追い込み設定 ---
dpo_trainer = DPOTrainer(
    model = model,
    ref_model = None,
    args = DPOConfig(
        per_device_train_batch_size = 1,
        gradient_accumulation_steps = 16,
        warmup_ratio = 0.1,
        num_train_epochs = 1,            # すでに覚えてるデータだから1〜2周で十分！
        learning_rate = 2e-6,            # 最後にグイッと引き上げる
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        output_dir = "outputs_V8_final_push",
        beta = 0.01,                     # 0.1から0.01へ。Qwenの「囲い癖」を力ずくで剥がす設定
        report_to = "none",
        remove_unused_columns = False,
    ),
    train_dataset = train_dataset,
    eval_dataset = eval_dataset,
    tokenizer = tokenizer,
    max_length = 1024,
    max_prompt_length = 512,
)

print("🚀 0.80の壁を壊しにいこう！学習開始！")
dpo_trainer.train()

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
Unsloth: WARNING `trust_remote_code` is True.
Are you certain you want to do remote code execution?
==((====))==  Unsloth 2026.1.4: Fast Qwen3 patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/3.55G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/237 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/707 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

Unsloth 2026.1.4 patched 36 layers with 36 QKV layers, 36 O layers and 36 MLP layers.

🔄 前回の最高傑作（0.77）の知能を注入中...

adapter_model.safetensors:   0%|          | 0.00/132M [00:00<?, ?B/s]

Extracting prompt in train dataset (num_proc=4):   0%|          | 0/225 [00:00<?, ? examples/s]

Applying chat template to train dataset (num_proc=4):   0%|          | 0/225 [00:00<?, ? examples/s]

Tokenizing train dataset (num_proc=4):   0%|          | 0/225 [00:00<?, ? examples/s]

Extracting prompt in eval dataset (num_proc=4):   0%|          | 0/25 [00:00<?, ? examples/s]

Applying chat template to eval dataset (num_proc=4):   0%|          | 0/25 [00:00<?, ? examples/s]

Tokenizing eval dataset (num_proc=4):   0%|          | 0/25 [00:00<?, ? examples/s]

🚀 0.80の壁を壊しにいこう！学習開始！

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 225 | Num Epochs = 1 | Total steps = 15
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 16
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 16 x 1) = 16
 "-____-"     Trainable parameters = 33,030,144 of 4,055,498,240 (0.81% trained)

Unsloth: Will smartly offload gradients to save VRAM!

TrainOutput(global_step=15, training_loss=0.23566920459270477, metrics={'train_runtime': 761.194, 'train_samples_per_second': 0.296, 'train_steps_per_second': 0.02, 'total_flos': 0.0, 'train_loss': 0.23566920459270477, 'epoch': 1.0})

## モデルの保存

In [ ]:
import os

# 1. 保存パスの設定（struct-eval-comp プロジェクト用）
adapter_name = "struct-eval-comp-dpo-v8"
drive_save_path = f"/content/drive/MyDrive/LLM2026/main_competition/DPO/{adapter_name}"
hf_model_id = "satoyutaka/LLM2025_main_0_DPO8" # 自分のHFユーザー名に合わせてね

# 2. Google ドライブへ保存
print(f"💾 Googleドライブに保存中: {drive_save_path}")
os.makedirs(drive_save_path, exist_ok=True)
model.save_pretrained(drive_save_path)
tokenizer.save_pretrained(drive_save_path)

# 3. Hugging Face へアップロード
print(f"🚀 Hugging Faceにアップロード中: {hf_model_id}")
try:
    model.push_to_hub(hf_model_id)
    tokenizer.push_to_hub(hf_model_id)
    print("✅ HFへのアップロードも完了したよ！")
except Exception as e:
    print(f"⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: {e}")

print("\n✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！")

💾 Googleドライブに保存中: /content/drive/MyDrive/LLM2026/main_competition/DPO/struct-eval-comp-dpo-v8
🚀 Hugging Faceにアップロード中: satoyutaka/LLM2025_main_0_DPO8

README.md:   0%|          | 0.00/31.0 [00:00<?, ?B/s]

⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: (Request ID: Root=1-69877859-5c7882f974eaea502e3838db;c95756be-5f47-4571-b6d6-fc1133941683)

403 Forbidden: Forbidden: you must use a write token to upload to a repository..
Cannot access content at: https://huggingface.co/api/models/satoyutaka/LLM2025_main_0_DPO8/preupload/main.
Make sure your token has the correct permissions.

✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！

# 9回目

In [ ]:
# 1. ライブラリを最新に更新して、衝突を解消するよ！
!pip install --upgrade huggingface_hub unsloth

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (0.36.2)
Collecting huggingface_hub
  Using cached huggingface_hub-1.4.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: unsloth in /usr/local/lib/python3.12/dist-packages (2026.1.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.20.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.5.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.21.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: unsloth_zoo>=2026.1.4 in /usr/local/lib/python3.12/dist-packages (from unsloth) (2026.1.4)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.46.3)
Requirement already satisfied: torch>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.9.0+cu126)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.24.0+cu126)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.9.5)
Requirement already satisfied: tyro in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.0.6)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.29.5)
Requirement already satisfied: xformers>=0.0.27.post2 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.0.33.post1)
Requirement already satisfied: bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.49.1)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (3.5.0)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.2.1)
Requirement already satisfied: datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.3.0)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.4.0)
Requirement already satisfied: peft!=0.11.0,>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.18.1)
Requirement already satisfied: hf_transfer in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.1.9)
Requirement already satisfied: diffusers in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.36.0)
Requirement already satisfied: transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,<=4.57.6,>=4.51.3 in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.56.2)
Requirement already satisfied: trl!=0.19.0,<=0.24.0,>=0.18.2 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.34.1->unsloth) (0.7.0)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (23.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.70.16)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.11.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,<=4.57.6,>=4.51.3->unsloth) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,<=4.57.6,>=4.51.3->unsloth) (0.22.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.5.0)
Requirement already satisfied: torchao>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (0.15.0)
Requirement already satisfied: cut_cross_entropy in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (25.1.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (11.3.0)
Requirement already satisfied: msgspec in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (0.20.0)
Requirement already satisfied: importlib_metadata in /usr/local/lib/python3.12/dist-packages (from diffusers->unsloth) (8.7.1)
Requirement already satisfied: docstring-parser>=0.15 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (0.17.0)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (4.4.4)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.13.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.4.0->unsloth) (1.3.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata->diffusers->unsloth) (3.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.4.0->unsloth) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.17.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface_hub) (8.3.1)

🚀 DPO学習：V9 構造知能の復元とスタイル最適化（中庸の設定）
このセルでは、前回の V8 で発生した「構造（Schema）の崩壊」という課題を解決し、最高スコア（0.77136）を超えるための**「バランス調整フェーズ」**を実行します。

1. V8 の分析と V9 の戦略

V8 では Beta 値を 0.01 まで下げた結果、Markdown 記号の排除には成功しましたが、引き換えにモデルが複雑なネスト構造を維持する能力（論理的整合性）を失い、スコアが 0.71 まで低下しました。 V9 では、**「知能を壊さずに、不要な装飾だけを削ぎ落とす」**ために、DPO の制約を緩和し、より安定した学習を目指します。

2. ハイパーパラメータの再最適化

Beta = 0.06（黄金比の探索）: V7（0.1：保守的）と V8（0.01：過激）の中間にあたる 0.06 を採用します。これにより、Qwen 本来の「高い構造化能力」を呼び戻しつつ、Markdown 囲いを「好ましくないもの」として認識させる絶妙なバランスを維持します。

Learning Rate = 1e-6: 学習率を V7 の成功時と同じ水準に戻します。急激な変化を避け、モデルが「思考（Approach）」を伴いながら「生のデータ」を出力する習慣をじわじわと定着させます。

Num Epochs = 2: 1 エポックでは定着しきれなかった「マナー」を、2 エポックかけて丁寧に教育します。

3. 学習の期待値

V9 の狙いは、**「V7 の知能（0.77）」＋「V8 のクリーンな見た目」**の合体です。 思考プロセス（Approach）を飛ばさずに実行させ、かつ最終的な Output: セクションからバッククォートを排除することで、パースエラーによる失点を防ぎ、目標の 0.80 突破を狙います。

## データのロード

In [ ]:
from datasets import load_dataset

# 1. 保存したjsonlファイルを読み込む
# 先ほどのスクリプトと同じディレクトリにあることを想定しているよ
data_files = {
    "train": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/struct_special_7_dpo_train.jsonl",
    "eval": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/struct_special_7_dpo_eval.jsonl"
}

# json形式でロード
dataset = load_dataset("json", data_files=data_files)

# 2. train と eval に切り分け
train_dataset = dataset["train"]
eval_dataset = dataset["eval"]

# 3. 中身の確認（デバッグ用：最初の1件を表示）
print("--- Train Dataset Sample ---")
print(train_dataset[0])
print(f"\nTrain size: {len(train_dataset)}, Eval size: {len(eval_dataset)}")

--- Train Dataset Sample ---
{'prompt': '### Instruction:\n<|im_start|>system\nYou are a helpful assistant. Please format your response as follows:\nApproach: <step-by-step reasoning>\nOutput: <final answer><|im_end|>\n<|im_start|>user\nOutput api specification as XML.<|im_end|>\n<|im_start|>assistant\n\n\n### Response:\n', 'chosen': 'Approach:\n1. Task: Create api specification in XML\n2. Complexity: medium - 5-8 fields, 2-3 levels\n3. Format rules: well-formed tags, proper nesting, escaped special chars\n4. Structure: Organize data logically with appropriate nesting\n5. Populate fields with realistic example data based on the schema.\n\nOutput:\n<?xml version="1.0" encoding="UTF-8"?>\n<api_specification>\n<openapi>3.0.0</openapi>\n<info>\n<title>Multi-lateral demand-driven matrices API</title>\n<version>1.0.0</version>\n</info>\n<paths>\n</speech>\n<get>\n<summary>According institution everybody bad listen nearly.</summary>\n<parameters>\n<name>param0</name>\n<in>query</in>\n<type>string</type>\n</parameters>\n<parameters>\n<name>param1</name>\n<in>query</in>\n<type>string</type>\n</parameters>\n<responses>\n<200>\n<description>Success</description>\n</200>\n<400>\n<description>Bad Request</description>\n</400>\n</responses>\n</get>\n<//speech>\n</paths>\n</api_specification>', 'rejected': 'Approach:  \n1. Understand the request: The user is asking to "output API specification as XML." This means they want a well-structured, machine-readable XML format that defines an API, typically including endpoints, methods, parameters, request/response formats, and other relevant details.  \n2. Create a generic but comprehensive API specification in XML format. This includes common elements like API version, base URL, endpoints, methods (GET, POST, etc.), parameters, and examples.  \n3. Ensure the XML is valid, properly nested, and follows standard conventions for API documentation (e.g., similar to OpenAPI/Swagger in XML form).  \n4. Avoid assumptions about specific services or technologies unless necessary—keep it general enough to be reusable.  \n\nOutput:  \n<apiSpecification>  \n  <api>  \n    <name>Sample REST API</name>  \n    <version>1.0</version>  \n    <baseURL>https://api.example.com/v1</baseURL>  \n    <description>Sample API for demonstrating data retrieval and submission.</description>  \n    <contact>  \n      <email>support@example.com</email>  \n      <website>https://example.com</website>  \n    </contact>  \n    <endpoints>  \n      <endpoint>  \n        <path>/users</path>  \n        <method>GET</method>  \n        <description>Retrieve a list of all users.</description>  \n        <parameters>  \n          <parameter>  \n            <name>page</name>  \n            <type>integer</type>  \n            <required>false</required>  \n            <description>Page number (default: 1).</description>  \n          </parameter>  \n          <parameter>  \n            <name>limit</name>  \n            <type>integer</type>  \n            <required>false</required>  \n            <description>Number of items per page (default: 10).</description>  \n          </parameter>  \n        </parameters>  \n        <response>  \n          <status>200</status>  \n          <contentType>application/json</contentType>  \n          <example>  \n            [{"id":1,"name":"Alice"},{"id":2,"name":"Bob"}]  \n          </example>  \n        </response>  \n      </endpoint>  \n      <endpoint>  \n        <path>/users/{id}</path>  \n        <method>GET</method>  \n        <description>Retrieve a specific user by ID.</description>  \n        <parameters>  \n          <parameter>  \n            <name>id</name>  \n            <type>integer</type>  \n            <required>true</required>  \n            <description>User ID.</description>  \n          </parameter>  \n        </parameters>  \n        <response>  \n          <status>200</status>  \n          <contentType>application/json</contentType>  \n          <example>  \n            {"id":1,"name":"Alice","email":"alice@example.com"}  \n          </example>  \n        </response>  \n      </endpoint>  \n      <endpoint>  \n        <path>/users</path>  \n        <method>POST</method>  \n        <description>Create a new user.</description>  \n        <request>  \n          <contentType>application/json</contentType>  \n          <example>  \n            {  \n              "name": "Charlie",  \n              "email": "charlie@example.com"  \n            }  \n          </example>  \n        </request>  \n        <response>  \n          <status>201</status>  \n          <contentType>application/json</contentType>  \n          <example>  \n            {"id":3,"name":"Charlie","email":"charlie@example.com"}  \n          </example>  \n        </response>  \n      </endpoint>  \n    </endpoints>  \n  </api>  \n</apiSpecification>', 'strategy': 'model_generated', 'logic_score': 12.187825202941895}

Train size: 225, Eval size: 25

## モデルのロードおよび学習

In [ ]:
from unsloth import FastLanguageModel, PatchDPOTrainer
import torch
from peft import set_peft_model_state_dict
from huggingface_hub import hf_hub_download
from safetensors.torch import load_file
from trl import DPOConfig, DPOTrainer

# --- 1. 事前パッチ ---
PatchDPOTrainer()

# --- 2. モデルロード ---
base_model_id = "Qwen/Qwen3-4B-Instruct-2507"
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = base_model_id,
    max_seq_length = 2048,
    load_in_4bit = True,
    trust_remote_code = True,
)

# --- 3. LoRA層の追加 ---
# Rank(r)を維持しつつ、学習効率を最大化するよ。
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
)

# --- 4. 0.77の重みを注入 (外科手術) ---
# 前回の最高傑作(DPO3/v6)の重みをロードして、ここをスタート地点にするよ！
print("🔄 前回の最高傑作（0.77）の知能を注入中...")
adapter_weights = hf_hub_download(repo_id="satoyutaka/LLM2025_main_0_DPO7", filename="adapter_model.safetensors")
state_dict = load_file(adapter_weights)
set_peft_model_state_dict(model, state_dict)

## --- V8: スパルタ追い込み設定 ---
dpo_trainer = DPOTrainer(
    model = model,
    ref_model = None,
    args = DPOConfig(
        per_device_train_batch_size = 1,
        gradient_accumulation_steps = 16,
        warmup_ratio = 0.1,
        num_train_epochs = 1,            # スタイルを覚えるために２回
        learning_rate = 1e-6,            # V7の成功した学習率に戻し、じわじわと定着させる。
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        output_dir = "outputs_V8_final_push",
        beta = 0.06,                     # 0.01は「極端」すぎた。少し余裕を持たせて知能を呼び戻す。
        report_to = "none",
        remove_unused_columns = False,
    ),
    train_dataset = train_dataset,
    eval_dataset = eval_dataset,
    tokenizer = tokenizer,
    max_length = 1024,
    max_prompt_length = 512,
)

print("🚀 0.80の壁を壊しにいこう！学習開始！")
dpo_trainer.train()

Unsloth: WARNING `trust_remote_code` is True.
Are you certain you want to do remote code execution?
==((====))==  Unsloth 2026.1.4: Fast Qwen3 patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
🔄 前回の最高傑作（0.77）の知能を注入中...
🚀 0.80の壁を壊しにいこう！学習開始！

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 225 | Num Epochs = 1 | Total steps = 15
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 16
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 16 x 1) = 16
 "-____-"     Trainable parameters = 33,030,144 of 4,055,498,240 (0.81% trained)

Unsloth: Will smartly offload gradients to save VRAM!

TrainOutput(global_step=15, training_loss=0.006667492154520005, metrics={'train_runtime': 741.0348, 'train_samples_per_second': 0.304, 'train_steps_per_second': 0.02, 'total_flos': 0.0, 'train_loss': 0.006667492154520005, 'epoch': 1.0})

## モデルの保存

In [ ]:
import os

# 1. 保存パスの設定（struct-eval-comp プロジェクト用）
adapter_name = "struct-eval-comp-dpo-v9"
drive_save_path = f"/content/drive/MyDrive/LLM2026/main_competition/DPO/{adapter_name}"
hf_model_id = "satoyutaka/LLM2025_main_0_DPO9" # 自分のHFユーザー名に合わせてね

# 2. Google ドライブへ保存
print(f"💾 Googleドライブに保存中: {drive_save_path}")
os.makedirs(drive_save_path, exist_ok=True)
model.save_pretrained(drive_save_path)
tokenizer.save_pretrained(drive_save_path)

# 3. Hugging Face へアップロード
print(f"🚀 Hugging Faceにアップロード中: {hf_model_id}")
try:
    model.push_to_hub(hf_model_id)
    tokenizer.push_to_hub(hf_model_id)
    print("✅ HFへのアップロードも完了したよ！")
except Exception as e:
    print(f"⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: {e}")

print("\n✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！")

💾 Googleドライブに保存中: /content/drive/MyDrive/LLM2026/main_competition/DPO/struct-eval-comp-dpo-v9
🚀 Hugging Faceにアップロード中: satoyutaka/LLM2025_main_0_DPO9
⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: (Request ID: Root=1-69878670-6712afe36c53b19662adebe2;be8a581e-9aae-4bf4-8c79-e60f573e14f5)

403 Forbidden: You don't have the rights to create a model under the namespace "satoyutaka".
Cannot access content at: https://huggingface.co/api/repos/create.
Make sure your token has the correct permissions.

✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！

# 10回目

In [ ]:
# 1. ライブラリを最新に更新して、衝突を解消するよ！
!pip install --upgrade huggingface_hub unsloth

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (0.36.2)
Collecting huggingface_hub
  Downloading huggingface_hub-1.4.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: unsloth in /usr/local/lib/python3.12/dist-packages (2025.12.7)
Collecting unsloth
  Downloading unsloth-2026.1.4-py3-none-any.whl.metadata (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 kB 3.4 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.20.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.5.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.21.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Collecting unsloth_zoo>=2026.1.4 (from unsloth)
  Downloading unsloth_zoo-2026.1.4-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.46.3)
Requirement already satisfied: torch>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.9.0+cu126)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.24.0+cu126)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.9.5)
Requirement already satisfied: tyro in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.0.6)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.29.5)
Requirement already satisfied: xformers>=0.0.27.post2 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.0.33.post1)
Requirement already satisfied: bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.49.1)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (3.5.0)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.2.1)
Requirement already satisfied: datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.3.0)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.4.0)
Collecting peft!=0.11.0,>=0.18.0 (from unsloth)
  Downloading peft-0.18.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: hf_transfer in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.1.9)
Requirement already satisfied: diffusers in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.36.0)
Requirement already satisfied: transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,<=4.57.6,>=4.51.3 in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.56.2)
Requirement already satisfied: trl!=0.19.0,<=0.24.0,>=0.18.2 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.34.1->unsloth) (0.7.0)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (23.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.70.16)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.11.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,<=4.57.6,>=4.51.3->unsloth) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,<=4.57.6,>=4.51.3->unsloth) (0.22.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.5.0)
Requirement already satisfied: torchao>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (0.15.0)
Requirement already satisfied: cut_cross_entropy in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (25.1.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (11.3.0)
Requirement already satisfied: msgspec in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (0.20.0)
Requirement already satisfied: importlib_metadata in /usr/local/lib/python3.12/dist-packages (from diffusers->unsloth) (8.7.1)
Requirement already satisfied: docstring-parser>=0.15 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (0.17.0)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (4.4.4)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.13.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.4.0->unsloth) (1.3.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata->diffusers->unsloth) (3.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.4.0->unsloth) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.17.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface_hub) (8.3.1)
Downloading unsloth-2026.1.4-py3-none-any.whl (405 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 405.7/405.7 kB 17.2 MB/s eta 0:00:00
Downloading peft-0.18.1-py3-none-any.whl (556 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.0/557.0 kB 35.2 MB/s eta 0:00:00
Downloading unsloth_zoo-2026.1.4-py3-none-any.whl (310 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 310.8/310.8 kB 16.8 MB/s eta 0:00:00
Installing collected packages: peft, unsloth_zoo, unsloth
  Attempting uninstall: peft
    Found existing installation: peft 0.13.2
    Uninstalling peft-0.13.2:
      Successfully uninstalled peft-0.13.2
  Attempting uninstall: unsloth_zoo
    Found existing installation: unsloth_zoo 2025.12.7
    Uninstalling unsloth_zoo-2025.12.7:
      Successfully uninstalled unsloth_zoo-2025.12.7
  Attempting uninstall: unsloth
    Found existing installation: unsloth 2025.12.7
    Uninstalling unsloth-2025.12.7:
      Successfully uninstalled unsloth-2025.12.7
Successfully installed peft-0.18.1 unsloth-2026.1.4 unsloth_zoo-2026.1.4

🚀 DPO学習：V10 最終調整フェーズ（知能と形式の黄金比）
このセルは、プロジェクト「struct-eval-comp」の集大成となる V10 学習プロセスです。 V8 (Beta 0.01) での構造崩壊と、V9 (Beta 0.06) での形式改善の停滞という極端な結果を分析し、「推論能力を一切削らずに、Markdownの癖だけを剥ぎ取る」 最適なパラメータを適用します。

1. V10 の戦略的ポジショニング

分析の結果、Qwen の構造化知能を維持しつつ Markdown バイアスを打破できる「スイートスポット」は Beta 値 0.03 〜 0.04 の間にあると推定されました。V10 ではその中心値である 0.035 を採用し、知能の安定と形式の矯正を両立させます。

2. ハイパーパラメータの最終最適化

Beta = 0.035: 0.01（過激）と 0.06（保守的）のギャップを埋める、本プロジェクトにおける「黄金比」設定です。

Learning Rate = 1e-6: V7/V9 での成功パターンを維持し、モデルの既存知能（0.77水準）を損なうことなく微調整を行います。

Num Epochs = 2: 2 回の反復により、1 回では剥がれきれなかった Markdown への依存を確実に排除します。

3. 期待される到達点

本学習の完走により、V7/V9 が持っていた「高い抽出精度」を保持したまま、V8 が見せた「クリーンな生データ出力」を実現し、スコア 0.80 の壁を突破することを最終目標とします。

## データのロード

In [ ]:
from datasets import load_dataset

# 1. 保存したjsonlファイルを読み込む
# 先ほどのスクリプトと同じディレクトリにあることを想定しているよ
data_files = {
    "train": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/struct_special_7_dpo_train.jsonl",
    "eval": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/struct_special_7_dpo_eval.jsonl"
}

# json形式でロード
dataset = load_dataset("json", data_files=data_files)

# 2. train と eval に切り分け
train_dataset = dataset["train"]
eval_dataset = dataset["eval"]

# 3. 中身の確認（デバッグ用：最初の1件を表示）
print("--- Train Dataset Sample ---")
print(train_dataset[0])
print(f"\nTrain size: {len(train_dataset)}, Eval size: {len(eval_dataset)}")

--- Train Dataset Sample ---
{'prompt': '### Instruction:\n<|im_start|>system\nYou are a helpful assistant. Please format your response as follows:\nApproach: <step-by-step reasoning>\nOutput: <final answer><|im_end|>\n<|im_start|>user\nOutput api specification as XML.<|im_end|>\n<|im_start|>assistant\n\n\n### Response:\n', 'chosen': 'Approach:\n1. Task: Create api specification in XML\n2. Complexity: medium - 5-8 fields, 2-3 levels\n3. Format rules: well-formed tags, proper nesting, escaped special chars\n4. Structure: Organize data logically with appropriate nesting\n5. Populate fields with realistic example data based on the schema.\n\nOutput:\n<?xml version="1.0" encoding="UTF-8"?>\n<api_specification>\n<openapi>3.0.0</openapi>\n<info>\n<title>Multi-lateral demand-driven matrices API</title>\n<version>1.0.0</version>\n</info>\n<paths>\n</speech>\n<get>\n<summary>According institution everybody bad listen nearly.</summary>\n<parameters>\n<name>param0</name>\n<in>query</in>\n<type>string</type>\n</parameters>\n<parameters>\n<name>param1</name>\n<in>query</in>\n<type>string</type>\n</parameters>\n<responses>\n<200>\n<description>Success</description>\n</200>\n<400>\n<description>Bad Request</description>\n</400>\n</responses>\n</get>\n<//speech>\n</paths>\n</api_specification>', 'rejected': 'Approach:  \n1. Understand the request: The user is asking to "output API specification as XML." This means they want a well-structured, machine-readable XML format that defines an API, typically including endpoints, methods, parameters, request/response formats, and other relevant details.  \n2. Create a generic but comprehensive API specification in XML format. This includes common elements like API version, base URL, endpoints, methods (GET, POST, etc.), parameters, and examples.  \n3. Ensure the XML is valid, properly nested, and follows standard conventions for API documentation (e.g., similar to OpenAPI/Swagger in XML form).  \n4. Avoid assumptions about specific services or technologies unless necessary—keep it general enough to be reusable.  \n\nOutput:  \n<apiSpecification>  \n  <api>  \n    <name>Sample REST API</name>  \n    <version>1.0</version>  \n    <baseURL>https://api.example.com/v1</baseURL>  \n    <description>Sample API for demonstrating data retrieval and submission.</description>  \n    <contact>  \n      <email>support@example.com</email>  \n      <website>https://example.com</website>  \n    </contact>  \n    <endpoints>  \n      <endpoint>  \n        <path>/users</path>  \n        <method>GET</method>  \n        <description>Retrieve a list of all users.</description>  \n        <parameters>  \n          <parameter>  \n            <name>page</name>  \n            <type>integer</type>  \n            <required>false</required>  \n            <description>Page number (default: 1).</description>  \n          </parameter>  \n          <parameter>  \n            <name>limit</name>  \n            <type>integer</type>  \n            <required>false</required>  \n            <description>Number of items per page (default: 10).</description>  \n          </parameter>  \n        </parameters>  \n        <response>  \n          <status>200</status>  \n          <contentType>application/json</contentType>  \n          <example>  \n            [{"id":1,"name":"Alice"},{"id":2,"name":"Bob"}]  \n          </example>  \n        </response>  \n      </endpoint>  \n      <endpoint>  \n        <path>/users/{id}</path>  \n        <method>GET</method>  \n        <description>Retrieve a specific user by ID.</description>  \n        <parameters>  \n          <parameter>  \n            <name>id</name>  \n            <type>integer</type>  \n            <required>true</required>  \n            <description>User ID.</description>  \n          </parameter>  \n        </parameters>  \n        <response>  \n          <status>200</status>  \n          <contentType>application/json</contentType>  \n          <example>  \n            {"id":1,"name":"Alice","email":"alice@example.com"}  \n          </example>  \n        </response>  \n      </endpoint>  \n      <endpoint>  \n        <path>/users</path>  \n        <method>POST</method>  \n        <description>Create a new user.</description>  \n        <request>  \n          <contentType>application/json</contentType>  \n          <example>  \n            {  \n              "name": "Charlie",  \n              "email": "charlie@example.com"  \n            }  \n          </example>  \n        </request>  \n        <response>  \n          <status>201</status>  \n          <contentType>application/json</contentType>  \n          <example>  \n            {"id":3,"name":"Charlie","email":"charlie@example.com"}  \n          </example>  \n        </response>  \n      </endpoint>  \n    </endpoints>  \n  </api>  \n</apiSpecification>', 'strategy': 'model_generated', 'logic_score': 12.187825202941895}

Train size: 225, Eval size: 25

## モデルのロードおよび学習

In [ ]:
from unsloth import FastLanguageModel, PatchDPOTrainer
import torch
from peft import set_peft_model_state_dict
from huggingface_hub import hf_hub_download
from safetensors.torch import load_file
from trl import DPOConfig, DPOTrainer

# --- 1. 事前パッチ ---
PatchDPOTrainer()

# --- 2. モデルロード ---
base_model_id = "Qwen/Qwen3-4B-Instruct-2507"
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = base_model_id,
    max_seq_length = 2048,
    load_in_4bit = True,
    trust_remote_code = True,
)

# --- 3. LoRA層の追加 ---
# Rank(r)を維持しつつ、学習効率を最大化するよ。
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
)

# --- 4. 0.77の重みを注入 (外科手術) ---
# 前回の最高傑作(DPO3/v6)の重みをロードして、ここをスタート地点にするよ！
print("🔄 前回の最高傑作（0.77）の知能を注入中...")
adapter_weights = hf_hub_download(repo_id="satoyutaka/LLM2025_main_0_DPO7", filename="adapter_model.safetensors")
state_dict = load_file(adapter_weights)
set_peft_model_state_dict(model, state_dict)

## --- V8: スパルタ追い込み設定 ---
dpo_trainer = DPOTrainer(
    model = model,
    ref_model = None, # Unslothの最適化を利用
    args = DPOConfig(
        per_device_train_batch_size = 1,
        gradient_accumulation_steps = 16,
        warmup_ratio = 0.1,
        num_train_epochs = 2,            # 2周で「マナー」を脳に定着させる
        learning_rate = 1e-6,            # 成功パターンの学習率を維持
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        output_dir = "outputs_V10_final_gold",
        beta = 0.035,                    # 知能(0.06)と矯正(0.01)の究極の妥協点！
        report_to = "none",
        remove_unused_columns = False,
        max_length = 1024,
        max_prompt_length = 512,
    ),
    train_dataset = train_dataset, # BERT厳選データ
    eval_dataset = eval_dataset,
    tokenizer = tokenizer,
)

print("🚀 0.80の壁を壊しにいこう！学習開始！")
dpo_trainer.train()

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
Unsloth: WARNING `trust_remote_code` is True.
Are you certain you want to do remote code execution?
==((====))==  Unsloth 2026.1.4: Fast Qwen3 patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/3.55G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/237 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/707 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

Unsloth 2026.1.4 patched 36 layers with 36 QKV layers, 36 O layers and 36 MLP layers.

🔄 前回の最高傑作（0.77）の知能を注入中...

adapter_model.safetensors:   0%|          | 0.00/132M [00:00<?, ?B/s]

Extracting prompt in train dataset (num_proc=4):   0%|          | 0/225 [00:00<?, ? examples/s]

Applying chat template to train dataset (num_proc=4):   0%|          | 0/225 [00:00<?, ? examples/s]

Tokenizing train dataset (num_proc=4):   0%|          | 0/225 [00:00<?, ? examples/s]

Extracting prompt in eval dataset (num_proc=4):   0%|          | 0/25 [00:00<?, ? examples/s]

Applying chat template to eval dataset (num_proc=4):   0%|          | 0/25 [00:00<?, ? examples/s]

Tokenizing eval dataset (num_proc=4):   0%|          | 0/25 [00:00<?, ? examples/s]

🚀 0.80の壁を壊しにいこう！学習開始！

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 225 | Num Epochs = 2 | Total steps = 30
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 16
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 16 x 1) = 16
 "-____-"     Trainable parameters = 33,030,144 of 4,055,498,240 (0.81% trained)

Unsloth: Will smartly offload gradients to save VRAM!

TrainOutput(global_step=30, training_loss=0.019361726505060992, metrics={'train_runtime': 1532.2621, 'train_samples_per_second': 0.294, 'train_steps_per_second': 0.02, 'total_flos': 0.0, 'train_loss': 0.019361726505060992, 'epoch': 2.0})

## モデルの保存

In [ ]:
import os

# 1. 保存パスの設定（struct-eval-comp プロジェクト用）
adapter_name = "struct-eval-comp-dpo-v10"
drive_save_path = f"/content/drive/MyDrive/LLM2026/main_competition/DPO/{adapter_name}"
hf_model_id = "satoyutaka/LLM2025_main_0_DPO10" # 自分のHFユーザー名に合わせてね

# 2. Google ドライブへ保存
print(f"💾 Googleドライブに保存中: {drive_save_path}")
os.makedirs(drive_save_path, exist_ok=True)
model.save_pretrained(drive_save_path)
tokenizer.save_pretrained(drive_save_path)

# 3. Hugging Face へアップロード
print(f"🚀 Hugging Faceにアップロード中: {hf_model_id}")
try:
    model.push_to_hub(hf_model_id)
    tokenizer.push_to_hub(hf_model_id)
    print("✅ HFへのアップロードも完了したよ！")
except Exception as e:
    print(f"⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: {e}")

print("\n✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！")

💾 Googleドライブに保存中: /content/drive/MyDrive/LLM2026/main_competition/DPO/struct-eval-comp-dpo-v10
🚀 Hugging Faceにアップロード中: satoyutaka/LLM2025_main_0_DPO10
⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: (Request ID: Root=1-6987be1d-75ab81793206e17845e6a58e;be09a801-a743-4ca2-90d2-5e56e8971238)

403 Forbidden: You don't have the rights to create a model under the namespace "satoyutaka".
Cannot access content at: https://huggingface.co/api/repos/create.
Make sure your token has the correct permissions.

✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！

# 11回目

🚀 DPO学習：V11 最終一点突破（低学習率・高圧スタイルの融合）
このセルでは、V10までの試行錯誤をすべて凝縮した**「V11：ハイブリッド・スパルタ」**を実行します。 Qwenの強固なMarkdownバイアスを打破するため、あえて全層（All Modules）をターゲットに戻しつつ、学習率を極限まで下げることで、既存の構造化能力（0.77水準）を固定したまま形式だけを矯正します。

1. V11 の設計思想：なぜ「全層 ＋ 低Beta ＋ 低LR」なのか？

全層ターゲット: V10（MLP限定）ではMarkdown癖が抜けなかったことから、このバイアスはAttention層の出力生成ロジックにも深く根ざしていると判断しました。

低Beta (0.025): V10 (0.035) で変化がなかったため、さらに圧力を強めます。ただし、崩壊を招いた 0.01 までは下げず、知能を維持できるギリギリのラインを攻めます。

低学習率 (5e-7): 通常の半分以下の学習率に設定します。これにより、モデルの脳を急激に書き換えるのではなく、「今の賢さを保ったまま、バッククォートだけをソッと外す」という繊細な調整を可能にします。

2. 学習の期待値

V11の狙いは、V7/V9/V10で停滞している「バッククォート119件」という壁を物理的に破壊することです。 論理構造を司るAttention層を「微振動」させることで、構造を保ったまま、不要な装飾（Markdown）だけを削ぎ落とし、スコア 0.80 の大台への到達を目指します。

In [ ]:
# 1. ライブラリを最新に更新して、衝突を解消するよ！
!pip install --upgrade huggingface_hub unsloth

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (0.36.2)
Collecting huggingface_hub
  Downloading huggingface_hub-1.4.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: unsloth in /usr/local/lib/python3.12/dist-packages (2025.12.7)
Collecting unsloth
  Downloading unsloth-2026.1.4-py3-none-any.whl.metadata (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 kB 3.4 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.20.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.5.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.21.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Collecting unsloth_zoo>=2026.1.4 (from unsloth)
  Downloading unsloth_zoo-2026.1.4-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.46.3)
Requirement already satisfied: torch>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.9.0+cu126)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.24.0+cu126)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.9.5)
Requirement already satisfied: tyro in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.0.6)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.29.5)
Requirement already satisfied: xformers>=0.0.27.post2 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.0.33.post1)
Requirement already satisfied: bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.49.1)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (3.5.0)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.2.1)
Requirement already satisfied: datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.3.0)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.4.0)
Collecting peft!=0.11.0,>=0.18.0 (from unsloth)
  Downloading peft-0.18.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: hf_transfer in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.1.9)
Requirement already satisfied: diffusers in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.36.0)
Requirement already satisfied: transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,<=4.57.6,>=4.51.3 in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.56.2)
Requirement already satisfied: trl!=0.19.0,<=0.24.0,>=0.18.2 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.34.1->unsloth) (0.7.0)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (23.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.70.16)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.11.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,<=4.57.6,>=4.51.3->unsloth) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,<=4.57.6,>=4.51.3->unsloth) (0.22.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.5.0)
Requirement already satisfied: torchao>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (0.15.0)
Requirement already satisfied: cut_cross_entropy in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (25.1.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (11.3.0)
Requirement already satisfied: msgspec in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.1.4->unsloth) (0.20.0)
Requirement already satisfied: importlib_metadata in /usr/local/lib/python3.12/dist-packages (from diffusers->unsloth) (8.7.1)
Requirement already satisfied: docstring-parser>=0.15 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (0.17.0)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (4.4.4)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.13.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.4.0->unsloth) (1.3.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata->diffusers->unsloth) (3.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.4.0->unsloth) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.17.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface_hub) (8.3.1)
Downloading unsloth-2026.1.4-py3-none-any.whl (405 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 405.7/405.7 kB 17.2 MB/s eta 0:00:00
Downloading peft-0.18.1-py3-none-any.whl (556 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.0/557.0 kB 35.2 MB/s eta 0:00:00
Downloading unsloth_zoo-2026.1.4-py3-none-any.whl (310 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 310.8/310.8 kB 16.8 MB/s eta 0:00:00
Installing collected packages: peft, unsloth_zoo, unsloth
  Attempting uninstall: peft
    Found existing installation: peft 0.13.2
    Uninstalling peft-0.13.2:
      Successfully uninstalled peft-0.13.2
  Attempting uninstall: unsloth_zoo
    Found existing installation: unsloth_zoo 2025.12.7
    Uninstalling unsloth_zoo-2025.12.7:
      Successfully uninstalled unsloth_zoo-2025.12.7
  Attempting uninstall: unsloth
    Found existing installation: unsloth 2025.12.7
    Uninstalling unsloth-2025.12.7:
      Successfully uninstalled unsloth-2025.12.7
Successfully installed peft-0.18.1 unsloth-2026.1.4 unsloth_zoo-2026.1.4

## データのロード

In [ ]:
from datasets import load_dataset

# 1. 保存したjsonlファイルを読み込む
# 先ほどのスクリプトと同じディレクトリにあることを想定しているよ
data_files = {
    "train": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/struct_special_7_dpo_train.jsonl",
    "eval": "/content/drive/MyDrive/LLM2026/main_competition/DPO_data/struct_special_7_dpo_eval.jsonl"
}

# json形式でロード
dataset = load_dataset("json", data_files=data_files)

# 2. train と eval に切り分け
train_dataset = dataset["train"]
eval_dataset = dataset["eval"]

# 3. 中身の確認（デバッグ用：最初の1件を表示）
print("--- Train Dataset Sample ---")
print(train_dataset[0])
print(f"\nTrain size: {len(train_dataset)}, Eval size: {len(eval_dataset)}")

--- Train Dataset Sample ---
{'prompt': '### Instruction:\n<|im_start|>system\nYou are a helpful assistant. Please format your response as follows:\nApproach: <step-by-step reasoning>\nOutput: <final answer><|im_end|>\n<|im_start|>user\nOutput api specification as XML.<|im_end|>\n<|im_start|>assistant\n\n\n### Response:\n', 'chosen': 'Approach:\n1. Task: Create api specification in XML\n2. Complexity: medium - 5-8 fields, 2-3 levels\n3. Format rules: well-formed tags, proper nesting, escaped special chars\n4. Structure: Organize data logically with appropriate nesting\n5. Populate fields with realistic example data based on the schema.\n\nOutput:\n<?xml version="1.0" encoding="UTF-8"?>\n<api_specification>\n<openapi>3.0.0</openapi>\n<info>\n<title>Multi-lateral demand-driven matrices API</title>\n<version>1.0.0</version>\n</info>\n<paths>\n</speech>\n<get>\n<summary>According institution everybody bad listen nearly.</summary>\n<parameters>\n<name>param0</name>\n<in>query</in>\n<type>string</type>\n</parameters>\n<parameters>\n<name>param1</name>\n<in>query</in>\n<type>string</type>\n</parameters>\n<responses>\n<200>\n<description>Success</description>\n</200>\n<400>\n<description>Bad Request</description>\n</400>\n</responses>\n</get>\n<//speech>\n</paths>\n</api_specification>', 'rejected': 'Approach:  \n1. Understand the request: The user is asking to "output API specification as XML." This means they want a well-structured, machine-readable XML format that defines an API, typically including endpoints, methods, parameters, request/response formats, and other relevant details.  \n2. Create a generic but comprehensive API specification in XML format. This includes common elements like API version, base URL, endpoints, methods (GET, POST, etc.), parameters, and examples.  \n3. Ensure the XML is valid, properly nested, and follows standard conventions for API documentation (e.g., similar to OpenAPI/Swagger in XML form).  \n4. Avoid assumptions about specific services or technologies unless necessary—keep it general enough to be reusable.  \n\nOutput:  \n<apiSpecification>  \n  <api>  \n    <name>Sample REST API</name>  \n    <version>1.0</version>  \n    <baseURL>https://api.example.com/v1</baseURL>  \n    <description>Sample API for demonstrating data retrieval and submission.</description>  \n    <contact>  \n      <email>support@example.com</email>  \n      <website>https://example.com</website>  \n    </contact>  \n    <endpoints>  \n      <endpoint>  \n        <path>/users</path>  \n        <method>GET</method>  \n        <description>Retrieve a list of all users.</description>  \n        <parameters>  \n          <parameter>  \n            <name>page</name>  \n            <type>integer</type>  \n            <required>false</required>  \n            <description>Page number (default: 1).</description>  \n          </parameter>  \n          <parameter>  \n            <name>limit</name>  \n            <type>integer</type>  \n            <required>false</required>  \n            <description>Number of items per page (default: 10).</description>  \n          </parameter>  \n        </parameters>  \n        <response>  \n          <status>200</status>  \n          <contentType>application/json</contentType>  \n          <example>  \n            [{"id":1,"name":"Alice"},{"id":2,"name":"Bob"}]  \n          </example>  \n        </response>  \n      </endpoint>  \n      <endpoint>  \n        <path>/users/{id}</path>  \n        <method>GET</method>  \n        <description>Retrieve a specific user by ID.</description>  \n        <parameters>  \n          <parameter>  \n            <name>id</name>  \n            <type>integer</type>  \n            <required>true</required>  \n            <description>User ID.</description>  \n          </parameter>  \n        </parameters>  \n        <response>  \n          <status>200</status>  \n          <contentType>application/json</contentType>  \n          <example>  \n            {"id":1,"name":"Alice","email":"alice@example.com"}  \n          </example>  \n        </response>  \n      </endpoint>  \n      <endpoint>  \n        <path>/users</path>  \n        <method>POST</method>  \n        <description>Create a new user.</description>  \n        <request>  \n          <contentType>application/json</contentType>  \n          <example>  \n            {  \n              "name": "Charlie",  \n              "email": "charlie@example.com"  \n            }  \n          </example>  \n        </request>  \n        <response>  \n          <status>201</status>  \n          <contentType>application/json</contentType>  \n          <example>  \n            {"id":3,"name":"Charlie","email":"charlie@example.com"}  \n          </example>  \n        </response>  \n      </endpoint>  \n    </endpoints>  \n  </api>  \n</apiSpecification>', 'strategy': 'model_generated', 'logic_score': 12.187825202941895}

Train size: 225, Eval size: 25

## モデルのロードおよび学習

In [ ]:
from unsloth import FastLanguageModel, PatchDPOTrainer
import torch
from peft import set_peft_model_state_dict
from huggingface_hub import hf_hub_download
from safetensors.torch import load_file
from trl import DPOConfig, DPOTrainer

# --- 1. 事前パッチ ---
PatchDPOTrainer()

# --- 2. モデルロード ---
base_model_id = "Qwen/Qwen3-4B-Instruct-2507"
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = base_model_id,
    max_seq_length = 2048,
    load_in_4bit = True,
    trust_remote_code = True,
)

# # --- 3. LoRA層の追加 ---
# # Rank(r)を維持しつつ、学習効率を最大化するよ。
# model = FastLanguageModel.get_peft_model(
#     model,
#     r = 16,
#     target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
#     lora_alpha = 16,
#     lora_dropout = 0,
#     bias = "none",
#     use_gradient_checkpointing = "unsloth",
#     random_state = 3407,
# )
# --- V11: MLP限定・スタイル一点突破設定 ---
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["gate_proj", "up_proj", "down_proj"], # MLPに集中
    lora_alpha = 32, # 影響力を高める
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
)

# Trainer設定：Betaを0.02まで攻める
# args.beta = 0.02
# --- 4. 0.77の重みを注入 (外科手術) ---
# 前回の最高傑作(DPO3/v6)の重みをロードして、ここをスタート地点にするよ！
print("🔄 前回の最高傑作（0.77）の知能を注入中...")
adapter_weights = hf_hub_download(repo_id="satoyutaka/LLM2025_main_0_DPO7", filename="adapter_model.safetensors")
state_dict = load_file(adapter_weights)
set_peft_model_state_dict(model, state_dict)

dpo_trainer = DPOTrainer(
    model = model,
    ref_model = None,
    args = DPOConfig(
        per_device_train_batch_size = 1,
        gradient_accumulation_steps = 16,
        warmup_ratio = 0.1,
        num_train_epochs = 1,            # 知能を壊さないよう、短く鋭く1エポック
        learning_rate = 5e-7,            # 極限まで低くし、既存の知能を「固定」
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        output_dir = "outputs_V11_surgical_strike",
        beta = 0.025,                    # V10より強く、V8より優しく。
        report_to = "none",
        remove_unused_columns = False,
        max_length = 1024,
        max_prompt_length = 512,
    ),
    train_dataset = train_dataset,
    eval_dataset = eval_dataset,
    tokenizer = tokenizer,
)

print("🚀 0.80の壁を壊しにいこう！学習開始！")
dpo_trainer.train()

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
Unsloth: WARNING `trust_remote_code` is True.
Are you certain you want to do remote code execution?
==((====))==  Unsloth 2026.1.4: Fast Qwen3 patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Not an error, but Unsloth cannot patch Attention layers with our manual autograd engine since either LoRA adapters
are not enabled or a bias term (like in Qwen) is used.
Not an error, but Unsloth cannot patch O projection layer with our manual autograd engine since either LoRA adapters
are not enabled or a bias term (like in Qwen) is used.
Unsloth 2026.1.4 patched 36 layers with 0 QKV layers, 0 O layers and 36 MLP layers.

🔄 前回の最高傑作（0.77）の知能を注入中...
🚀 0.80の壁を壊しにいこう！学習開始！

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 225 | Num Epochs = 1 | Total steps = 15
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 16
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 16 x 1) = 16
 "-____-"     Trainable parameters = 21,233,664 of 4,043,701,760 (0.53% trained)

Unsloth: Will smartly offload gradients to save VRAM!

TrainOutput(global_step=15, training_loss=0.09078663537899653, metrics={'train_runtime': 755.9393, 'train_samples_per_second': 0.298, 'train_steps_per_second': 0.02, 'total_flos': 0.0, 'train_loss': 0.09078663537899653, 'epoch': 1.0})

## モデルの保存

In [ ]:
import os

# 1. 保存パスの設定（struct-eval-comp プロジェクト用）
adapter_name = "struct-eval-comp-dpo-v11"
drive_save_path = f"/content/drive/MyDrive/LLM2026/main_competition/DPO/{adapter_name}"
hf_model_id = "satoyutaka/LLM2025_main_0_DPO11" # 自分のHFユーザー名に合わせてね

# 2. Google ドライブへ保存
print(f"💾 Googleドライブに保存中: {drive_save_path}")
os.makedirs(drive_save_path, exist_ok=True)
model.save_pretrained(drive_save_path)
tokenizer.save_pretrained(drive_save_path)

# 3. Hugging Face へアップロード
print(f"🚀 Hugging Faceにアップロード中: {hf_model_id}")
try:
    model.push_to_hub(hf_model_id)
    tokenizer.push_to_hub(hf_model_id)
    print("✅ HFへのアップロードも完了したよ！")
except Exception as e:
    print(f"⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: {e}")

print("\n✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！")

💾 Googleドライブに保存中: /content/drive/MyDrive/LLM2026/main_competition/DPO/struct-eval-comp-dpo-v11
🚀 Hugging Faceにアップロード中: satoyutaka/LLM2025_main_0_DPO11

README.md: 0.00B [00:00, ?B/s]

⚠️ HFアップロードでエラーが出たけど、ドライブには保存されてるよ: (Request ID: Root=1-6987c79a-077731cb7d57ff167a665576;fcb7dbe7-7c41-440e-b96a-df2a42b77420)

403 Forbidden: Forbidden: you must use a write token to upload to a repository..
Cannot access content at: https://huggingface.co/api/models/satoyutaka/LLM2025_main_0_DPO11/preupload/main.
Make sure your token has the correct permissions.

✨ すべての保存工程が完了しました！お疲れ様、ゆーちゃ！